#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierCompraContestadaTransacaoResponse
@end

@interface PierCompraContestadaTransacaoResponse : PierObject


@property(nonatomic) NSNumber* agingCompras;

@property(nonatomic) NSNumber* agingContestacao;

@property(nonatomic) NSString* bandeira;

@property(nonatomic) NSString* codigoAutorizacao;

@property(nonatomic) NSString* codigoContestacao;

@property(nonatomic) NSString* codigoEventoCompra;

@property(nonatomic) NSString* codigoMoedaDestino;

@property(nonatomic) NSString* data2Reapresentacao;

@property(nonatomic) NSDate* dataAlteracao;

@property(nonatomic) NSDate* dataContestacao;

@property(nonatomic) NSString* dataEnvioCB;

@property(nonatomic) NSDate* dataTransacao;

@property(nonatomic) NSNumber* idCompraContestada;

@property(nonatomic) NSNumber* internacional;

@property(nonatomic) NSString* mcc;

@property(nonatomic) NSString* modoDeEntradaDescricao;

@property(nonatomic) NSString* modoEntrada;

@property(nonatomic) NSString* motivo2Reapresentacao;

@property(nonatomic) NSString* nomeEstabelecimento;

@property(nonatomic) NSString* numeroControle;

@property(nonatomic) NSString* razaoCB;

@property(nonatomic) NSString* referenceNumber;

@property(nonatomic) NSString* reporteBandeira;

@property(nonatomic) NSString* responsavelAbertuda;

@property(nonatomic) NSString* responsavelAlteracao;

@property(nonatomic) NSString* statusContestacao;

@property(nonatomic) NSString* texto2Reapresentacao;

@property(nonatomic) NSString* tipoTransacao;

@property(nonatomic) NSString* transacaoSegura;

@property(nonatomic) NSNumber* valorCompra;

@property(nonatomic) NSNumber* valorContrato;

@property(nonatomic) NSNumber* valorDestino;

@end
