#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierNotificacaoResponse
@end

@interface PierNotificacaoResponse : PierObject

/* N\u00FAmero do protocolo de envio de notifica\u00E7\u00F5es [optional]
 */
@property(nonatomic) NSString* protocolo;
/* Mensagem de resposta da solicita\u00E7\u00F5es de envio [optional]
 */
@property(nonatomic) NSString* mensagem;

@end
