#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTipoAjusteResponse
@end

@interface PierTipoAjusteResponse : PierObject

/* C\u00C3\u00B3digo identificador do tipo de ajuste. [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Descri\u00C3\u00A7\u00C3\u00A3o do tipo de ajuste. [optional]
 */
@property(nonatomic) NSString* descricao;

@end
