#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierStatusOportunidadeAUDResponse
@end

@interface PierStatusOportunidadeAUDResponse : PierObject

/* C\u00C3\u00B3digo identificador da auditoria dos tipos oportunidades [optional]
 */
@property(nonatomic) NSNumber* rev;
/* C\u00C3\u00B3digo que representa o tipo de a\u00C3\u00A7\u00C3\u00A3o realizada no recurso de tipos oportunidades [optional]
 */
@property(nonatomic) NSNumber* revType;
/* Data da a\u00C3\u00A7\u00C3\u00A3o realizada no recurso de tipos oportunidades [optional]
 */
@property(nonatomic) NSString* revDate;
/* C\u00C3\u00B3digo identificador do StatusOportunidade [optional]
 */
@property(nonatomic) NSNumber* _id;
/* C\u00C3\u00B3digo identificador do TipoOportunidade [optional]
 */
@property(nonatomic) NSNumber* idTipoOportunidade;
/* Nome do status oportunidade [optional]
 */
@property(nonatomic) NSString* nome;
/* Descricao do StatusOportunidade [optional]
 */
@property(nonatomic) NSString* descricao;
/* Flag que representa se o tipo oportunidade est\u00C3\u00A1 ativo [optional]
 */
@property(nonatomic) NSNumber* flagAtivo;

@end
