#import <Foundation/Foundation.h>
#import "PierDocumentoTemplatePersist.h"
#import "PierDocumentoTemplateResponse.h"
#import "PierPageDocumentoTemplateResponse.h"
#import "PierDocumentoResponse.h"
#import "PierDocumentoParametrosRequest.h"
#import "PierDocumentoTipoResponse.h"
#import "PierDocumentoTipoRequest.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierDocumentoApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierDocumentoApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierDocumentoApi*) sharedAPI;
///
///
/// Atualizar templates dos documentos
/// Esse recurso permite atualizar templates dos documentos.
///
/// @param _id C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do documento template (id).
/// @param persist persist
/// 
///
/// @return PierDocumentoTemplateResponse*
-(NSNumber*) atualizarUsingPUTWithId: (NSNumber*) _id
    persist: (PierDocumentoTemplatePersist*) persist
    completionHandler: (void (^)(PierDocumentoTemplateResponse* output, NSError* error)) handler;


///
///
/// Consultar templates dos documentos
/// Esse recurso permite consultar templates dos documentos.
///
/// @param _id C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do documento template (id).
/// 
///
/// @return PierDocumentoTemplateResponse*
-(NSNumber*) consultarUsingGET7WithId: (NSNumber*) _id
    completionHandler: (void (^)(PierDocumentoTemplateResponse* output, NSError* error)) handler;


///
///
/// Lista os templates dos documentos
/// Esse recurso permite listar os templates dos documentos.
///
/// @param sort Tipo de ordena\u00C3\u00A7\u00C3\u00A3o dos registros.
/// @param page P\u00C3\u00A1gina solicitada (Default = 0)
/// @param limit Limite de elementos por solicita\u00C3\u00A7\u00C3\u00A3o (Default = 50, Max = 50)
/// @param idTipoDocumento C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do tipo do documento.
/// 
///
/// @return PierPageDocumentoTemplateResponse*
-(NSNumber*) listarUsingGET10WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    idTipoDocumento: (NSNumber*) idTipoDocumento
    completionHandler: (void (^)(PierPageDocumentoTemplateResponse* output, NSError* error)) handler;


///
///
/// Cadastra documentos
/// Esse recurso permite cadastrar documentos.
///
/// @param persist persist
/// 
///
/// @return PierDocumentoResponse*
-(NSNumber*) salvarUsingPOST5WithPersist: (PierDocumentoParametrosRequest*) persist
    completionHandler: (void (^)(PierDocumentoResponse* output, NSError* error)) handler;


///
///
/// Cadastra os templates dos documentos
/// Esse recurso permite cadastrar templates dos documentos.
///
/// @param persist persist
/// 
///
/// @return PierDocumentoTemplateResponse*
-(NSNumber*) salvarUsingPOST6WithPersist: (PierDocumentoTemplatePersist*) persist
    completionHandler: (void (^)(PierDocumentoTemplateResponse* output, NSError* error)) handler;


///
///
/// Cadastra os tipos de documentos
/// Esse recurso permite cadastrar tipos de documentos.
///
/// @param persist persist
/// 
///
/// @return PierDocumentoTipoResponse*
-(NSNumber*) salvarUsingPOST7WithPersist: (PierDocumentoTipoRequest*) persist
    completionHandler: (void (^)(PierDocumentoTipoResponse* output, NSError* error)) handler;



@end
