#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierEmprestimoPessoalRequest
@end

@interface PierEmprestimoPessoalRequest : PierObject

/* Valor do empr\u00E9stimo/financiamento 
 */
@property(nonatomic) NSNumber* valorSolicitado;
/* N\u00FAmero total de parcelas do empr\u00E9stimo/financiamento 
 */
@property(nonatomic) NSNumber* numeroParcelas;
/* Valor percentual da taxa de juros a ser aplicada 
 */
@property(nonatomic) NSNumber* taxaJuros;
/* Per\u00EDodo de aplica da taxa de juros 
 */
@property(nonatomic) NSString* periodoTaxa;
/* Sistema para amortiza\u00E7\u00E3o do valor das parcelas 
 */
@property(nonatomic) NSString* sistemaAmortizacao;
/* N\u00FAmero de meses para cobran\u00E7a da primeira parcela [optional]
 */
@property(nonatomic) NSNumber* numeroMesesCarencia;

@end
