#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierContaBancariaPortadorUpdateValue_
@end

@interface PierContaBancariaPortadorUpdateValue_ : PierObject

/* {{{conta_bancaria_portador_update_nome_agencia_value}}} [optional]
 */
@property(nonatomic) NSString* nomeAgencia;
/* {{{conta_bancaria_portador_update_banco_value}}} 
 */
@property(nonatomic) NSNumber* banco;
/* {{{conta_bancaria_portador_update_numero_agencia_value}}} 
 */
@property(nonatomic) NSString* numeroAgencia;
/* {{{conta_bancaria_portador_update_digito_agencia_value}}} [optional]
 */
@property(nonatomic) NSString* digitoAgencia;
/* {{{conta_bancaria_portador_update_numero_conta_value}}} 
 */
@property(nonatomic) NSString* numeroConta;
/* {{{conta_bancaria_portador_update_digito_conta_value}}} [optional]
 */
@property(nonatomic) NSString* digitoConta;
/* {{{conta_bancaria_portador_update_flag_ativo_value}}} 
 */
@property(nonatomic) NSNumber* flagAtivo;
/* {{{conta_bancaria_portador_update_flag_conta_origem_doc_value}}} 
 */
@property(nonatomic) NSNumber* flagContaOrigemDoc;
/* {{{conta_bancaria_portador_update_flag_conta_poupanca_value}}} 
 */
@property(nonatomic) NSNumber* flagContaPoupanca;
/* {{{conta_bancaria_portador_update_favorecido_value}}} 
 */
@property(nonatomic) NSString* favorecido;
/* {{{conta_bancaria_portador_update_numero_receira_federal_value}}} 
 */
@property(nonatomic) NSString* numeroReceiraFederal;
/* {{{conta_bancaria_portador_update_titularidade_value}}} [optional]
 */
@property(nonatomic) NSNumber* titularidade;

@end
