#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierDadosPortadorRequest
@end

@interface PierDadosPortadorRequest : PierObject

/* {{{dados_portador_request_cartao_value}}} 
 */
@property(nonatomic) NSString* cartao;
/* {{{dados_portador_request_cpf_value}}} 
 */
@property(nonatomic) NSString* cpf;
/* {{{dados_portador_request_nome_value}}} [optional]
 */
@property(nonatomic) NSString* nome;
/* {{{dados_portador_request_data_nascimento_value}}} [optional]
 */
@property(nonatomic) NSString* dataNascimento;
/* {{{dados_portador_request_cep_residencial_value}}} 
 */
@property(nonatomic) NSString* cepResidencial;
/* {{{dados_portador_request_email_value}}} 
 */
@property(nonatomic) NSString* email;
/* {{{dados_portador_request_ddd_value}}} [optional]
 */
@property(nonatomic) NSString* ddd;
/* {{{dados_portador_request_telefone_value}}} [optional]
 */
@property(nonatomic) NSString* telefone;

@end
