#import <Foundation/Foundation.h>
#import "PierCancelarCartaoResponse.h"
#import "PierConsultarCartaoResponse.h"
#import "PierDesbloquearCartaoResponse.h"
#import "PierEmbossadoCartaoResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierCartaoApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierCartaoApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierCartaoApi*) sharedAPI;
///
///
/// Bloqueia um cart\u00C3\u00A3o
/// Bloquear um determinado cart\u00C3\u00A3o
///
/// @param idConta ID da Conta
/// @param idCartao ID do Cart\u00C3\u00A3o que deseja cancelar
/// @param motivo Motivo do bloqueio
/// @param observacao Alguma observa\u00C3\u00A7\u00C3\u00A3o para o bloqueio
/// 
///
/// @return PierCancelarCartaoResponse*
-(NSNumber*) bloquearCartaoUsingPOSTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    motivo: (NSNumber*) motivo
    observacao: (NSString*) observacao
    completionHandler: (void (^)(PierCancelarCartaoResponse* output, NSError* error)) handler;


///
///
/// Retorna um cart\u00C3\u00A3o
/// Consultar as informa\u00C3\u00A7\u00C3\u00B5es de um determinado cart\u00C3\u00A3o de uma conta
///
/// @param idConta ID da Conta que pertence o cart\u00C3\u00A3o
/// @param idCartao ID do Cart\u00C3\u00A3o que deseja consultar
/// @param numeroCartao N\u00C3\u00BAmero do Cart\u00C3\u00A3o que deseja consultar (opcional)
/// 
///
/// @return PierConsultarCartaoResponse*
-(NSNumber*) consultarCartaoUsingGETWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    numeroCartao: (NSString*) numeroCartao
    completionHandler: (void (^)(PierConsultarCartaoResponse* output, NSError* error)) handler;


///
///
/// Retorna todos os cart\u00C3\u00B5es
/// Consultar todos os cart\u00C3\u00B5es de uma determinada conta
///
/// @param idConta ID da Conta
/// 
///
/// @return PierConsultarCartaoResponse*
-(NSNumber*) consultarCartoesUsingGETWithIdConta: (NSNumber*) idConta
    completionHandler: (void (^)(PierConsultarCartaoResponse* output, NSError* error)) handler;


///
///
/// Desbloqueia um cart\u00C3\u00A3o
/// Desbloquear cart\u00C3\u00A3o de uma determinada conta
///
/// @param idConta ID da Conta
/// @param idCartao ID do Cart\u00C3\u00A3o que deseja consultar o saldo/limite
/// @param codigoSegurancao C\u00C3\u00B3digo seguran\u00C3\u00A7a do cart\u00C3\u00A3o
/// 
///
/// @return PierDesbloquearCartaoResponse*
-(NSNumber*) desbloquearCartaoUsingPOSTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    codigoSegurancao: (NSString*) codigoSegurancao
    completionHandler: (void (^)(PierDesbloquearCartaoResponse* output, NSError* error)) handler;


///
///
/// Embossado
/// N\u00C3\u00B3s informe caso tenha embossado algum cart\u00C3\u00A3o.
///
/// @param idConta ID da Conta
/// @param idCartao ID do Cart\u00C3\u00A3o que deseja cancelar
/// 
///
/// @return PierEmbossadoCartaoResponse*
-(NSNumber*) embossadoCartaoUsingPUTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(PierEmbossadoCartaoResponse* output, NSError* error)) handler;



@end
