#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTipoBoletoResponse
@end

@interface PierTipoBoletoResponse : PierObject

/* C\u00F3digo identificador do tipo de boleto. [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Descri\u00E7\u00E3o do tipo de boleto. [optional]
 */
@property(nonatomic) NSString* descricao;
/* C\u00F3digo identificador do banco. [optional]
 */
@property(nonatomic) NSNumber* banco;
/* Faixa permitida para cria\u00E7\u00E3o do nosso n\u00FAmero. [optional]
 */
@property(nonatomic) NSNumber* faixaNossoNumero;
/* N\u00FAmero minimo para o nosso n\u00FAmero. [optional]
 */
@property(nonatomic) NSNumber* minNossoNumero;
/* N\u00FAmero m\u00E1ximo para o nosso n\u00FAmero. [optional]
 */
@property(nonatomic) NSNumber* maxNossoNumero;
/* Tamanho do nosso n\u00FAmero. [optional]
 */
@property(nonatomic) NSNumber* tamNossoNumero;
/* \u00DAltimo nosso n\u00FAmero utilizado. [optional]
 */
@property(nonatomic) NSNumber* ultimoNossoNumero;

@end
