#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierAtribuirAssinaturaClientePersist
@end

@interface PierAtribuirAssinaturaClientePersist : PierObject

/* {{{atribuir_assinatura_cliente_persist_id_arquivo_value}}} [optional]
 */
@property(nonatomic) NSNumber* idArquivo;

@end
