#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierHistoricoTelefoneResponse
@end

@interface PierHistoricoTelefoneResponse : PierObject

/* C\u00F3digo de Identifica\u00E7\u00E3o do Telefone (id). [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Apresenta o N\u00FAmero do telefone. [optional]
 */
@property(nonatomic) NSString* telefone;
/* Apresenta o id do tipo do telefone. [optional]
 */
@property(nonatomic) NSNumber* idTipoTelefone;
/* Apresenta a descri\u00E7\u00E3o do tipo do telefone. [optional]
 */
@property(nonatomic) NSString* tipoTelefone;
/* Apresenta a data que o telefone fora alterado. [optional]
 */
@property(nonatomic) NSString* dataModificacao;

@end
