#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierAnexoNotificacaoEmailRequest
@end

@interface PierAnexoNotificacaoEmailRequest : PierObject

/* ID do documento que ser\u00E1 anexado a notifica\u00E7\u00E3o. [optional]
 */
@property(nonatomic) NSNumber* idDocumento;

@end
