#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierEnderecoAprovadoResponse.h"
#import "PierReferenciaComercialAprovadoResponse.h"
#import "PierSocioAprovadoResponse.h"
#import "PierTelefonePessoaAprovadaResponse.h"


@protocol PierPessoaJuridicaAprovadaResponse
@end

@interface PierPessoaJuridicaAprovadaResponse : PierObject

/* {{{pessoa_juridica_aprovada_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{pessoa_juridica_aprovada_response_razao_social_value}}} [optional]
 */
@property(nonatomic) NSString* razaoSocial;
/* {{{pessoa_juridica_aprovada_response_nome_fantasia_value}}} [optional]
 */
@property(nonatomic) NSString* nomeFantasia;
/* {{{pessoa_juridica_aprovada_response_cnpj_value}}} [optional]
 */
@property(nonatomic) NSString* cnpj;
/* {{{pessoa_juridica_aprovada_response_inscricao_estadual_value}}} [optional]
 */
@property(nonatomic) NSString* inscricaoEstadual;
/* {{{pessoa_juridica_aprovada_response_data_abertura_empresa_value}}} [optional]
 */
@property(nonatomic) NSString* dataAberturaEmpresa;
/* {{{pessoa_juridica_aprovada_response_id_origem_comercial_value}}} [optional]
 */
@property(nonatomic) NSNumber* idOrigemComercial;
/* {{{pessoa_juridica_aprovada_response_id_produto_value}}} [optional]
 */
@property(nonatomic) NSNumber* idProduto;
/* {{{pessoa_juridica_aprovada_response_numero_banco_value}}} [optional]
 */
@property(nonatomic) NSNumber* numeroBanco;
/* {{{pessoa_juridica_aprovada_response_numero_agencia_value}}} [optional]
 */
@property(nonatomic) NSNumber* numeroAgencia;
/* {{{pessoa_juridica_aprovada_response_numero_conta_corrente_value}}} [optional]
 */
@property(nonatomic) NSString* numeroContaCorrente;
/* {{{pessoa_juridica_aprovada_response_email_value}}} [optional]
 */
@property(nonatomic) NSString* email;
/* {{{pessoa_juridica_aprovada_response_dia_vencimento_value}}} [optional]
 */
@property(nonatomic) NSNumber* diaVencimento;
/* {{{pessoa_juridica_aprovada_response_nome_impresso_value}}} [optional]
 */
@property(nonatomic) NSString* nomeImpresso;
/* {{{pessoa_juridica_aprovada_response_id_conta_value}}} [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* {{{pessoa_juridica_aprovada_response_id_proposta_value}}} [optional]
 */
@property(nonatomic) NSNumber* idProposta;
/* {{{pessoa_juridica_aprovada_response_canal_entrada_value}}} [optional]
 */
@property(nonatomic) NSString* canalEntrada;
/* {{{pessoa_juridica_aprovada_response_valor_pontuacao_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorPontuacao;
/* {{{pessoa_juridica_aprovada_response_telefones_value}}} [optional]
 */
@property(nonatomic) NSArray<PierTelefonePessoaAprovadaResponse>* telefones;
/* {{{pessoa_juridica_aprovada_response_enderecos_value}}} [optional]
 */
@property(nonatomic) NSArray<PierEnderecoAprovadoResponse>* enderecos;
/* {{{pessoa_juridica_aprovada_response_socios_value}}} [optional]
 */
@property(nonatomic) NSArray<PierSocioAprovadoResponse>* socios;
/* {{{pessoa_juridica_aprovada_response_referencias_value}}} [optional]
 */
@property(nonatomic) NSArray<PierReferenciaComercialAprovadoResponse>* referencias;
/* {{{pessoa_juridica_aprovada_response_limite_global_value}}} 
 */
@property(nonatomic) NSNumber* limiteGlobal;
/* {{{pessoa_juridica_aprovada_response_limite_maximo_value}}} 
 */
@property(nonatomic) NSNumber* limiteMaximo;
/* {{{pessoa_juridica_aprovada_response_limite_parcelas_value}}} 
 */
@property(nonatomic) NSNumber* limiteParcelas;

@end
