#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierAlterarProdutoRequest
@end

@interface PierAlterarProdutoRequest : PierObject

/* C\u00C3\u00B3digo identificador do produto. 
 */
@property(nonatomic) NSNumber* idProduto;
/* C\u00C3\u00B3digo identificador da origem comercial. [optional]
 */
@property(nonatomic) NSNumber* idOrigemComercial;
/* Identificador do estabelecimento. [optional]
 */
@property(nonatomic) NSNumber* idEstabelecimento;
/* Identificador do promotor que realizou a solicita\u00C3\u00A7\u00C3\u00A3o do grade no estabelecimento. [optional]
 */
@property(nonatomic) NSNumber* idPromotor;

@end
