#import <Foundation/Foundation.h>
#import "PierObject.h"
#import "PierWebHook.h"
#import "PierPageWebHooks.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierWebhooksApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierWebhooksApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierWebhooksApi*) sharedAPI;
///
///
/// Alterar Webhook
/// Este m\u00C3\u00A9todo permite que seja modificado um webhooks j\u00C3\u00A1 cadastrado
///
/// @param _id C\u00C3\u00B3digo identificador do Webhook
/// @param evento Evento a ser chamado pelo WebHook
/// @param metodo M\u00C3\u00A9todo que a ser chamado pelo WebHook
/// @param url URL que a ser consumida pelo WebHook
/// 
///
/// @return PierWebHook*
-(NSNumber*) alterarUsingPUT2WithId: (NSNumber*) _id
    evento: (PierObject*) evento
    metodo: (PierObject*) metodo
    url: (NSString*) url
    completionHandler: (void (^)(PierWebHook* output, NSError* error)) handler;


///
///
/// Consultar Webhook
/// Este m\u00C3\u00A9todo permite que sejam consultado um webhook do emissor atrav\u00C3\u00A9s de um id especifico
///
/// @param _id C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Webhook (id).
/// 
///
/// @return PierWebHook*
-(NSNumber*) consultarUsingGET9WithId: (NSNumber*) _id
    completionHandler: (void (^)(PierWebHook* output, NSError* error)) handler;


///
///
/// Lista os Webhooks
/// Este m\u00C3\u00A9todo permite que sejam listados os webhooks existentes
///
/// @param _id Id do WebHook
/// @param evento Evento a ser chamado pelo WebHook
/// @param metodo M\u00C3\u00A9todo que a ser chamado pelo WebHook
/// @param url URL que a ser consumida pelo WebHook
/// @param page P\u00C3\u00A1gina solicitada (Default = 0)
/// @param limit Limite de elementos por solicita\u00C3\u00A7\u00C3\u00A3o (Default = 100, Max = 100)
/// 
///
/// @return PierPageWebHooks*
-(NSNumber*) listarUsingGET10WithId: (NSNumber*) _id
    evento: (PierObject*) evento
    metodo: (PierObject*) metodo
    url: (NSString*) url
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    completionHandler: (void (^)(PierPageWebHooks* output, NSError* error)) handler;


///
///
/// Salvar Webhook
/// Este m\u00C3\u00A9todo permite que seja adicionado um novo webhook
///
/// @param evento Evento a ser chamado pelo WebHook
/// @param metodo M\u00C3\u00A9todo que a ser chamado pelo WebHook
/// @param url URL que a ser consumida pelo WebHook
/// 
///
/// @return PierWebHook*
-(NSNumber*) salvarUsingPOST3WithEvento: (PierObject*) evento
    metodo: (PierObject*) metodo
    url: (NSString*) url
    completionHandler: (void (^)(PierWebHook* output, NSError* error)) handler;



@end
