#import <Foundation/Foundation.h>
#import "PierPaisResponse.h"
#import "PierPagePaisResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierPermissaoPaisesApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierPermissaoPaisesApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierPermissaoPaisesApi*) sharedAPI;
///
///
/// Apresenta dados de um determinado pa\u00C3\u00ADs
/// Este m\u00C3\u00A9todo permite consultar dados de um determinado pa\u00C3\u00ADs a partir de seu codigo de identifica\u00C3\u00A7\u00C3\u00A3o (id).
///
/// @param _id C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do pa\u00C3\u00ADs (id).
/// 
///
/// @return PierPaisResponse*
-(NSNumber*) consultarPaisUsingGETWithId: (NSNumber*) _id
    completionHandler: (void (^)(PierPaisResponse* output, NSError* error)) handler;


///
///
/// Lista os continentes
/// Este recurso permite listar os continentes utilizados no recurso de permiss\u00C3\u00A3o de uso do cart\u00C3\u00A3o no exterior
///
/// 
///
/// @return NSArray* /* NSObject */
-(NSNumber*) listarContinentesUsingGETWithCompletionHandler: 
    (void (^)(NSArray* /* NSObject */ output, NSError* error)) handler;


///
///
/// Lista os pa\u00C3\u00ADses
/// Este recurso permite listar os pa\u00C3\u00ADses.
///
/// @param page P\u00C3\u00A1gina solicitada (Default = 0)
/// @param limit Limite de elementos por solicita\u00C3\u00A7\u00C3\u00A3o (Default = 50, Max = 50)
/// @param codigo C\u00C3\u00B3digo do pa\u00C3\u00ADs
/// @param sigla Sigla do pa\u00C3\u00ADs
/// @param descricao Nome do pa\u00C3\u00ADs
/// @param continente Continente no qual o pa\u00C3\u00ADs faz parte
/// @param flagAtivo Atributo que representa se o pa\u00C3\u00ADs est\u00C3\u00A1 ativo
/// 
///
/// @return PierPagePaisResponse*
-(NSNumber*) listarPaisesUsingGETWithPage: (NSNumber*) page
    limit: (NSNumber*) limit
    codigo: (NSString*) codigo
    sigla: (NSString*) sigla
    descricao: (NSString*) descricao
    continente: (NSString*) continente
    flagAtivo: (NSNumber*) flagAtivo
    completionHandler: (void (^)(PierPagePaisResponse* output, NSError* error)) handler;



@end
