#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierAvisoViagemResponse
@end

@interface PierAvisoViagemResponse : PierObject

/* {{{aviso_viagem_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{aviso_viagem_response_id_cartao_value}}} [optional]
 */
@property(nonatomic) NSNumber* idCartao;
/* {{{aviso_viagem_response_codigo_pais_value}}} [optional]
 */
@property(nonatomic) NSString* codigoPais;
/* {{{aviso_viagem_response_data_inicio_value}}} [optional]
 */
@property(nonatomic) NSString* dataInicio;
/* {{{aviso_viagem_response_data_fim_value}}} [optional]
 */
@property(nonatomic) NSString* dataFim;
/* {{{aviso_viagem_response_flag_ativo_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagAtivo;

@end
