#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTipoFaturamentoPorContaPersistValue_
@end

@interface PierTipoFaturamentoPorContaPersistValue_ : PierObject

/* {{{tipo_faturamento_por_conta_persist_id_conta_value}}} 
 */
@property(nonatomic) NSNumber* idConta;
/* {{{tipo_faturamento_por_conta_persist_id_tipo_faturamento_value}}} 
 */
@property(nonatomic) NSNumber* idTipoFaturamento;

@end
