#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierPaisResponse
@end

@interface PierPaisResponse : PierObject

/* C\u00F3digo identificador \u00FAnico do pa\u00EDs na base [optional]
 */
@property(nonatomic) NSNumber* _id;
/* C\u00F3digo identificador do pa\u00EDs [optional]
 */
@property(nonatomic) NSString* codigo;
/* Sigla do pa\u00EDs [optional]
 */
@property(nonatomic) NSString* sigla;
/* Nome do pa\u00EDs [optional]
 */
@property(nonatomic) NSString* descricao;
/* Continente no qual o pa\u00EDs faz parte [optional]
 */
@property(nonatomic) NSString* continente;
/* Atributo que representa se o pa\u00EDs est\u00E1 ativo [optional]
 */
@property(nonatomic) NSNumber* flagAtivo;

@end
