#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTaxaAntecipacaoRequest
@end

@interface PierTaxaAntecipacaoRequest : PierObject

/* C\u00F3digo que identifica se um par\u00E2metro refere-se a uma transa\u00E7\u00E3o On-Us ou Off-Us. [optional]
 */
@property(nonatomic) NSString* tipoTransacao;
/* Valor da Taxa de Antecipa\u00E7\u00E3o. [optional]
 */
@property(nonatomic) NSNumber* valorTaxa;

@end
