#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierPushAPNSPersistValue_
@end

@interface PierPushAPNSPersistValue_ : PierObject

/* {{{push_a_p_n_s_persist_id_pessoa_value}}} 
 */
@property(nonatomic) NSNumber* idPessoa;
/* {{{push_a_p_n_s_persist_id_conta_value}}} 
 */
@property(nonatomic) NSNumber* idConta;
/* {{{push_a_p_n_s_persist_token_dispositivo_value}}} 
 */
@property(nonatomic) NSString* tokenDispositivo;
/* {{{push_a_p_n_s_persist_certificado_value}}} 
 */
@property(nonatomic) NSString* certificado;
/* {{{push_a_p_n_s_persist_senha_value}}} 
 */
@property(nonatomic) NSString* senha;
/* {{{push_a_p_n_s_persist_titulo_value}}} 
 */
@property(nonatomic) NSString* titulo;
/* {{{push_a_p_n_s_persist_conteudo_value}}} 
 */
@property(nonatomic) NSString* conteudo;
/* {{{push_f_c_m_g_c_m_persist_tipo_evento_value}}} 
 */
@property(nonatomic) NSString* tipoEvento;
/* {{{push_f_c_m_g_c_m_persist_icone_value}}} [optional]
 */
@property(nonatomic) NSString* icone;
/* {{{push_f_c_m_g_c_m_persist_som_value}}} [optional]
 */
@property(nonatomic) NSString* som;

@end
