#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierAnexoNotificacaoEmailRequest.h"


@protocol PierNotificacaoEmailRequest
@end

@interface PierNotificacaoEmailRequest : PierObject

/* ID para o template da notifica\u00E7\u00E3o. [optional]
 */
@property(nonatomic) NSNumber* idTemplateNotificacao;
/* Lista de email(s) do(s) destinat\u00E1rio(s). [optional]
 */
@property(nonatomic) NSArray* /* NSString */ destinatarios;
/* Lista de ids dos anexos a serem enviados. [optional]
 */
@property(nonatomic) NSArray<PierAnexoNotificacaoEmailRequest>* anexos;
/* Mapa de par\u00E2metros para montagem da notifica\u00E7\u00E3o. [optional]
 */
@property(nonatomic) NSDictionary* /* NSString, NSObject */ parametrosConteudo;

@end
