#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierLocalDateTime.h"


@protocol PierCartaoResponse
@end

@interface PierCartaoResponse : PierObject

/* Apresenta o nome do arquivo onde o cart\u00C3\u00A3o fora inclu\u00C3\u00ADdo para impress\u00C3\u00A3o por uma gr\u00C3\u00A1fica, quando houver. 
 */
@property(nonatomic) NSString* arquivoImpressao;
/* Apresenta um c\u00C3\u00B3digo espec\u00C3\u00ADfico para ser utilizado como vari\u00C3\u00A1vel no processo de desbloqueio do cart\u00C3\u00A3o para emissores que querem usar esta funcionalidade. 
 */
@property(nonatomic) NSString* codigoDesbloqueio;
/* Apresenta a data em que o idEstagioCartao atual do cart\u00C3\u00A3o fora aplicado, quando houver. 
 */
@property(nonatomic) PierLocalDateTime* dataEstagioCartao;
/* Apresenta a data em que o cart\u00C3\u00A3o foi gerado. 
 */
@property(nonatomic) PierLocalDateTime* dataGeracao;
/* Apresenta a data em que o cart\u00C3\u00A3o fora impresso, caso impress\u00C3\u00A3o em loja, ou a data em que ele fora inclu\u00C3\u00ADdo no arquivo para impress\u00C3\u00A3o via gr\u00C3\u00A1fica. 
 */
@property(nonatomic) PierLocalDateTime* dataImpressao;
/* Apresenta a data em que o idStatusCartao atual do cart\u00C3\u00A3o fora aplicado, quando houver. 
 */
@property(nonatomic) PierLocalDateTime* dataStatusCartao;
/* Apresenta a data de validade do cart\u00C3\u00A3o em formato MMAAAA, quando houver. 
 */
@property(nonatomic) PierLocalDateTime* dataValidade;
/* Quando ativa, indica que o cart\u00C3\u00A3o fora impresso na Origem Comercial. 
 */
@property(nonatomic) NSNumber* flagImpressaoOrigemComercial;
/* Quando ativa, indica que o cart\u00C3\u00A3o \u00C3\u00A9 provis\u00C3\u00B3rio. Ou seja, \u00C3\u00A9 um cart\u00C3\u00A3o para uso tempor\u00C3\u00A1rio quando se deseja permitir que o cliente transacione sem que ele tenha recebido um cart\u00C3\u00A3o definitivo. 
 */
@property(nonatomic) NSNumber* flagProvisorio;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Cart\u00C3\u00A3o (id). 
 */
@property(nonatomic) NSNumber* _id;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o da Conta a qual o cart\u00C3\u00A3o pertence (id). 
 */
@property(nonatomic) NSNumber* idConta;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Est\u00C3\u00A1gio de Impress\u00C3\u00A3o do Cart\u00C3\u00A3o (id). 
 */
@property(nonatomic) NSNumber* idEstagioCartao;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o da Pessoa a qual o cart\u00C3\u00A3o pertence (id) 
 */
@property(nonatomic) NSNumber* idPessoa;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Status do Cart\u00C3\u00A3o (id). 
 */
@property(nonatomic) NSNumber* idStatusCartao;
/* Apresenta o n\u00C3\u00BAmero do cart\u00C3\u00A3o. 
 */
@property(nonatomic) NSString* numeroCartao;
/* Indica qual \u00C3\u00A9 a rela\u00C3\u00A7\u00C3\u00A3o do portador do cart\u00C3\u00A3o com a conta. Quando \u00E2\u0080\u00981\u00E2\u0080\u0099, corresponde ao seu titular. Quando diferente disso, corresponde a um cart\u00C3\u00A3o adicional. 
 */
@property(nonatomic) NSNumber* portador;

@end
