#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierDetalheOportunidadeResponse.h"


@protocol PierOportunidadeResponse
@end

@interface PierOportunidadeResponse : PierObject

/* C\u00F3digo identificador da oportunidade [optional]
 */
@property(nonatomic) NSNumber* _id;
/* C\u00F3digo identificador do tipo oportunidade [optional]
 */
@property(nonatomic) NSNumber* idTipoOportunidade;
/* C\u00F3digo identificador do status oportunidade [optional]
 */
@property(nonatomic) NSNumber* idStatusOportunidade;
/* Data cadastro da oportunidade. [optional]
 */
@property(nonatomic) NSString* dataCadastro;
/* Data atualiza\u00E7\u00E3o da oportunidade. [optional]
 */
@property(nonatomic) NSString* dataAtualizacao;
/* N\u00FAmero receita federal do cliente ao qual ser\u00E1 ofertada a oportunidade [optional]
 */
@property(nonatomic) NSString* numeroReceitaFederal;
/* In\u00EDcio da vig\u00EAncia da oportunidade [optional]
 */
@property(nonatomic) NSString* dataInicioVigencia;
/* Fim da vig\u00EAncia da oportunidade [optional]
 */
@property(nonatomic) NSString* dataFimVigencia;
/* Flag de verifica\u00E7\u00E3o se a oportunidade est\u00E1 ativa [optional]
 */
@property(nonatomic) NSNumber* flagAtivo;
/* Lista de detalhes da oportunidade [optional]
 */
@property(nonatomic) NSArray<PierDetalheOportunidadeResponse>* detalhes;

@end
