#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierParcelamentoTransferenciaResponse
@end

@interface PierParcelamentoTransferenciaResponse : PierObject

/* {{{parcelamento_transferencia_response_numero_parcela_value}}} [optional]
 */
@property(nonatomic) NSNumber* numeroParcela;
/* {{{parcelamento_transferencia_response_valor_parcelas_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorParcelas;
/* {{{parcelamento_transferencia_response_valor_total_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorTotal;
/* {{{parcelamento_transferencia_response_valor_t_a_c_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorTAC;
/* {{{parcelamento_transferencia_response_valor_i_o_f_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorIOF;
/* {{{parcelamento_transferencia_response_taxa_juros_value}}} [optional]
 */
@property(nonatomic) NSNumber* taxaJuros;
/* {{{parcelamento_transferencia_response_cet_anual_value}}} [optional]
 */
@property(nonatomic) NSNumber* cetAnual;

@end
