#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierEstGioCartO.h"


@protocol PierListaDeEstGiosCartEs
@end

@interface PierListaDeEstGiosCartEs : PierObject

/* Lista de est\u00C3\u00A1gios cart\u00C3\u00B5es [optional]
 */
@property(nonatomic) NSArray<PierEstGioCartO>* estagiosCartoes;

@end
