#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierVinculoOperacaoPersist
@end

@interface PierVinculoOperacaoPersist : PierObject

/* C\u00F3digo de Identifica\u00E7\u00E3o do Produto (id). [optional]
 */
@property(nonatomic) NSNumber* idProduto;
/* C\u00F3digo de Identifica\u00E7\u00E3o da Opera\u00E7\u00E3o (id). [optional]
 */
@property(nonatomic) NSNumber* idOperacao;
/* C\u00F3digo MCC. [optional]
 */
@property(nonatomic) NSNumber* codigoMCC;

@end
