#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierTelefonePessoaAprovadaPersistValue_.h"


@protocol PierSocioAprovadoPersistValue_
@end

@interface PierSocioAprovadoPersistValue_ : PierObject

/* {{{socio_aprovado_persist_nome_value}}} 
 */
@property(nonatomic) NSString* nome;
/* {{{socio_aprovado_persist_cpf_value}}} [optional]
 */
@property(nonatomic) NSString* cpf;
/* {{{socio_aprovado_persist_data_nascimento_value}}} [optional]
 */
@property(nonatomic) NSString* dataNascimento;
/* {{{socio_aprovado_persist_sexo_value}}} [optional]
 */
@property(nonatomic) NSString* sexo;
/* {{{socio_aprovado_persist_numero_identidade_value}}} [optional]
 */
@property(nonatomic) NSString* numeroIdentidade;
/* {{{socio_aprovado_persist_orgao_expedidor_identidade_value}}} [optional]
 */
@property(nonatomic) NSString* orgaoExpedidorIdentidade;
/* {{{socio_aprovado_persist_unidade_federativa_identidade_value}}} [optional]
 */
@property(nonatomic) NSString* unidadeFederativaIdentidade;
/* {{{socio_aprovado_persist_data_emissao_identidade_value}}} [optional]
 */
@property(nonatomic) NSString* dataEmissaoIdentidade;
/* {{{socio_aprovado_persist_estado_civil_value}}} [optional]
 */
@property(nonatomic) NSString* estadoCivil;
/* {{{socio_aprovado_persist_profissao_value}}} [optional]
 */
@property(nonatomic) NSString* profissao;
/* {{{socio_aprovado_persist_nacionalidade_value}}} [optional]
 */
@property(nonatomic) NSString* nacionalidade;
/* {{{socio_aprovado_persist_email_value}}} [optional]
 */
@property(nonatomic) NSString* email;
/* {{{socio_aprovado_persist_telefones_value}}} [optional]
 */
@property(nonatomic) NSArray<PierTelefonePessoaAprovadaPersistValue_>* telefones;

@end
