#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierRiscoFraudeResponse
@end

@interface PierRiscoFraudeResponse : PierObject

/* C\u00F3digo de identifica\u00E7\u00E3o do risco de fraude [optional]
 */
@property(nonatomic) NSNumber* _id;
/* C\u00F3digo de identifica\u00E7\u00E3o do tipo de resolu\u00E7\u00E3o atribu\u00EDdo ao registro [optional]
 */
@property(nonatomic) NSNumber* idTipoResolucao;
/* Descri\u00E7\u00E3o do tipo de resolu\u00E7\u00E3o atribu\u00EDdo ao registro [optional]
 */
@property(nonatomic) NSString* descricaoTipoResolucao;
/* Quando ativa, indica que a transa\u00E7\u00E3o possui um alto risco de fraude e que todas as transa\u00E7\u00F5es seguintes a ela ser\u00E3o negadas at\u00E9 que todas as transa\u00E7\u00F5es classificadas com risco de fraude sejam analisadas [optional]
 */
@property(nonatomic) NSNumber* flagAltoRisco;
/* C\u00F3digo de identifica\u00E7\u00E3o da conta [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* C\u00F3digo de identifica\u00E7\u00E3o do cart\u00E3o [optional]
 */
@property(nonatomic) NSNumber* idCartao;
/* C\u00F3digo de identifica\u00E7\u00E3o da transa\u00E7\u00E3o [optional]
 */
@property(nonatomic) NSNumber* idTransacao;
/* Data em que a transa\u00E7\u00E3o classificada com risco de fraude foi realizada [optional]
 */
@property(nonatomic) NSString* dataTransacao;
/* Valor da transa\u00E7\u00E3o classificada com risco de fraude [optional]
 */
@property(nonatomic) NSNumber* valorTransacao;
/* Valor da transa\u00E7\u00E3o classificada com risco de fraude [optional]
 */
@property(nonatomic) NSString* nomeEstabelecimento;

@end
