#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierPlanoParcelamentoTransferenciaResponse.h"


@protocol PierPlanoParcelamentoTransferenciaCreditoContaBancariaResponse
@end

@interface PierPlanoParcelamentoTransferenciaCreditoContaBancariaResponse : PierObject

/* N\u00C3\u00BAmero Sequencial \u00C3\u009Anico que identifica a transa\u00C3\u00A7\u00C3\u00A3o no sistema que a originou. [optional]
 */
@property(nonatomic) NSString* nsuOrigem;
/* N\u00C3\u00BAmero Sequencial \u00C3\u009Anico gerado pelo Autorizador a cada Transa\u00C3\u00A7\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSString* nsuAutorizacao;
/* C\u00C3\u00B3digo de Autoriza\u00C3\u00A7\u00C3\u00A3o gerado pelo Autorizador. [optional]
 */
@property(nonatomic) NSString* codigoAutorizacao;
/* N\u00C3\u00BAmero do Cart\u00C3\u00A3o que originou a transa\u00C3\u00A7\u00C3\u00A3o em formato mascarado. [optional]
 */
@property(nonatomic) NSString* numeroMascaradoCartao;
/* Nome do Portador do Cart\u00C3\u00A3o que originou a transa\u00C3\u00A7\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSString* nomePortadorCartao;
/* Apresenta a identifica\u00C3\u00A7\u00C3\u00A3o do terminal requisitante [optional]
 */
@property(nonatomic) NSString* terminalRequisitante;
/* Lista os planos de parcelamentos [optional]
 */
@property(nonatomic) NSArray<PierPlanoParcelamentoTransferenciaResponse>* planoParcelamentos;

@end
