#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTransferenciaCreditoContaBancariaResponse
@end

@interface PierTransferenciaCreditoContaBancariaResponse : PierObject

/* C\u00F3digo de identifica\u00E7\u00E3o da transferencia. [optional]
 */
@property(nonatomic) NSNumber* idTransferencia;
/* Taxa de custo efetivo total. [optional]
 */
@property(nonatomic) NSNumber* valorCET;
/* C\u00F3digo de identifica\u00E7\u00E3o da autoriza\u00E7\u00E3o. [optional]
 */
@property(nonatomic) NSNumber* idAutorizacao;
/* C\u00F3digo da autoriza\u00E7\u00E3o. [optional]
 */
@property(nonatomic) NSString* codigoAutorizacao;
/* NSU de origem. [optional]
 */
@property(nonatomic) NSNumber* nsuOrigem;
/* C\u00F3digo de identifica\u00E7\u00E3o da conta. [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* C\u00F3digo de identifica\u00E7\u00E3o do cart\u00E3o. [optional]
 */
@property(nonatomic) NSNumber* idCartao;
/* C\u00F3digo de identifica\u00E7\u00E3o do tipo de opera\u00E7\u00E3o. [optional]
 */
@property(nonatomic) NSNumber* idOperacao;
/* Valor da transfer\u00EAncia. [optional]
 */
@property(nonatomic) NSNumber* valorCompra;
/* Valor da parcela. [optional]
 */
@property(nonatomic) NSNumber* valorParcela;
/* Valor da transfer\u00EAncia acrescido do valor da tarifa de saque se houver tarifa de saque. [optional]
 */
@property(nonatomic) NSNumber* valorContrato;
/* N\u00FAmero de parcelas. [optional]
 */
@property(nonatomic) NSNumber* numeroParcelas;
/* Valor do IOF. [optional]
 */
@property(nonatomic) NSNumber* valorIOF;
/* Valor da TAC. [optional]
 */
@property(nonatomic) NSNumber* valorTAC;
/* Valor da taxa saque. [optional]
 */
@property(nonatomic) NSNumber* valorTaxaSaque;
/* Percentual de juros. [optional]
 */
@property(nonatomic) NSNumber* taxaJuros;
/* Data da transfer\u00EAncia. [optional]
 */
@property(nonatomic) NSString* dataCompra;
/* Data do movimento. [optional]
 */
@property(nonatomic) NSString* dataMovimento;
/* Data do vencimento real da fatura. [optional]
 */
@property(nonatomic) NSString* dataVencimentoReal;
/* Dia do vencimento padr\u00E3o da fatura. [optional]
 */
@property(nonatomic) NSString* dataVencimentoPadrao;
/* Data da autoriza\u00E7\u00E3o. [optional]
 */
@property(nonatomic) NSString* dataAutorizacao;
/* C\u00F3digo do Banco. [optional]
 */
@property(nonatomic) NSNumber* banco;
/* N\u00FAmero da Ag\u00EAncia. [optional]
 */
@property(nonatomic) NSString* numeroAgencia;
/* D\u00EDgito da Ag\u00EAncia. [optional]
 */
@property(nonatomic) NSString* digitoAgencia;
/* N\u00FAmero da Conta. [optional]
 */
@property(nonatomic) NSString* numeroConta;
/* D\u00EDgito da Conta. [optional]
 */
@property(nonatomic) NSString* digitoConta;
/* Tipo da Conta. [optional]
 */
@property(nonatomic) NSNumber* flagContaPoupanca;
/* Documento do Favorecido. [optional]
 */
@property(nonatomic) NSString* documentoFavorecido;
/* Nome do Favorecido. [optional]
 */
@property(nonatomic) NSString* nomeFavorecido;
/* C\u00F3digo do Status [optional]
 */
@property(nonatomic) NSString* status;
/* Status Processamento. [optional]
 */
@property(nonatomic) NSString* statusProcessamento;

@end
