#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTipoFaturamentoPorContaPersist
@end

@interface PierTipoFaturamentoPorContaPersist : PierObject

/* Representa se a configura\u00C3\u00A7\u00C3\u00A3o est\u00C3\u00A1 ativada ou desativada para a conta. 
 */
@property(nonatomic) NSNumber* status;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da conta relacionada. 
 */
@property(nonatomic) NSNumber* idConta;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do tipo de faturamento relacionada. 
 */
@property(nonatomic) NSNumber* idTipoFaturamento;
/* Data da inclus\u00C3\u00A3o da configura\u00C3\u00A7\u00C3\u00A3o, deve ser informada no formato yyyy-MM-dd'T'HH:mm:ss.SSS'Z'. [optional]
 */
@property(nonatomic) NSString* dataHoraInclusao;
/* Data do cancelamento da configura\u00C3\u00A7\u00C3\u00A3o, deve ser informada no formato yyyy-MM-dd'T'HH:mm:ss.SSS'Z'. [optional]
 */
@property(nonatomic) NSString* dataHoraCancelamento;
/* Identificador do respons\u00C3\u00A1vel pela modifica\u00C3\u00A7\u00C3\u00A3o do registro. 
 */
@property(nonatomic) NSString* modificadoPor;

@end
