#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierHistoricoAtrasoFaturaResponse
@end

@interface PierHistoricoAtrasoFaturaResponse : PierObject

/* Data vencimento fatura. [optional]
 */
@property(nonatomic) NSDate* dataVencimento;
/* Quantidade de dias em atraso. [optional]
 */
@property(nonatomic) NSNumber* diasPagamentoAposVencimento;

@end
