#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierAntecipacaoSimuladaResponse.h"


@protocol PierAntecipacaoSimuladaLoteResponse
@end

@interface PierAntecipacaoSimuladaLoteResponse : PierObject

/* {{{antecipacao_simulada_lote_response_valor_total_antecipado_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorTotalAntecipado;
/* {{{antecipacao_simulada_lote_response_valor_total_desconto_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorTotalDesconto;
/* {{{antecipacao_simulada_lote_response_valor_total_com_desconto_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorTotalComDesconto;
/* {{{antecipacao_simulada_lote_response_antecipacoes_simuladas_value}}} [optional]
 */
@property(nonatomic) NSArray<PierAntecipacaoSimuladaResponse>* antecipacoesSimuladas;

@end
