#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierCartaoPayKeyUpdate
@end

@interface PierCartaoPayKeyUpdate : PierObject

/* {{{cartao_pay_key_update_chave_criptograma_value}}} 
 */
@property(nonatomic) NSString* chaveCriptograma;

@end
