#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierReferenciaIdPersist.h"


@protocol PierDocumentoTemplatePersist
@end

@interface PierDocumentoTemplatePersist : PierObject

/* {{{documento_template_persist_id_tipo_template_value}}} [optional]
 */
@property(nonatomic) NSNumber* idTipoTemplate;
/* {{{documento_template_persist_template_value}}} [optional]
 */
@property(nonatomic) NSString* template;
/* {{{documento_template_persist_integracoes_value}}} [optional]
 */
@property(nonatomic) NSArray<PierReferenciaIdPersist>* integracoes;

@end
