#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTipoResolucaoResponse
@end

@interface PierTipoResolucaoResponse : PierObject

/* {{{tipo_resolucao_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{tipo_resolucao_response_descricao_value}}} [optional]
 */
@property(nonatomic) NSString* descricao;

@end
