#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierMaquinetaPersist
@end

@interface PierMaquinetaPersist : PierObject

/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Terminal (id). 
 */
@property(nonatomic) NSNumber* idTerminal;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Tipo Maquineta (id). 
 */
@property(nonatomic) NSNumber* idTipoMaquineta;
/* Valor de Manuten\u00C3\u00A7\u00C3\u00A3o da Maquineta. 
 */
@property(nonatomic) NSNumber* valor;
/* Data da implanta\u00C3\u00A7\u00C3\u00A3o da Maquineta, inserir no formato yyyy-MM-dd'T'HH:mm:ss.SSS'Z'. 
 */
@property(nonatomic) NSString* dataHoraImplantacao;

@end
