#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTerminalResponse
@end

@interface PierTerminalResponse : PierObject

/* C\u00F3digo de Identifica\u00E7\u00E3o do Terminal (id). [optional]
 */
@property(nonatomic) NSNumber* _id;
/* N\u00FAmero \u00FAnico do terminal. [optional]
 */
@property(nonatomic) NSString* terminal;
/* N\u00FAmero do estabelecimento a qual o terminal pertence. [optional]
 */
@property(nonatomic) NSNumber* numeroEstabelecimento;
/* N\u00FAmero de identifica\u00E7\u00E3o do estabelecimento a qual o terminal pertence. [optional]
 */
@property(nonatomic) NSNumber* idEstabelecimento;
/* Flag indicando se o terminal \u00E9 f\u00EDsico ou virtual, sendo: (true: Sim), (false: N\u00E3o)). [optional]
 */
@property(nonatomic) NSNumber* flagConsultaExtrato;
/* Flag indicando se o terminal permite consultar extrato, sendo: (true: Sim), (false: N\u00E3o)). [optional]
 */
@property(nonatomic) NSNumber* flagTerminalVirtual;

@end
