#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierStatusContestacaoResponse
@end

@interface PierStatusContestacaoResponse : PierObject

/* {{{status_contestacao_request_idstatuscontestacao_value}}} [optional]
 */
@property(nonatomic) NSNumber* idStatusContestacao;
/* {{{status_contestacao_response_descricao_value}}} [optional]
 */
@property(nonatomic) NSString* descricao;

@end
