#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierAntecipacaoResponse
@end

@interface PierAntecipacaoResponse : PierObject

/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da antecipa\u00C3\u00A7\u00C3\u00A3o [optional]
 */
@property(nonatomic) NSNumber* _id;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da conta [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da compra [optional]
 */
@property(nonatomic) NSNumber* idCompra;
/* Apresenta o numero total de parcelas da comprae [optional]
 */
@property(nonatomic) NSNumber* quantidadeParcelasTotal;
/* Apresenta o numero de parcelas antecipadas [optional]
 */
@property(nonatomic) NSNumber* quantidadeParcelasAntecipadas;
/* Apresenta o valor das parcelas efetivadas [optional]
 */
@property(nonatomic) NSNumber* valorParcelas;

@end
