#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierBaseUpdateValue_
@end

@interface PierBaseUpdateValue_ : PierObject

/* {{{base_update_servidor_value}}} 
 */
@property(nonatomic) NSString* servidor;
/* {{{base_update_usuario_value}}} 
 */
@property(nonatomic) NSString* usuario;
/* {{{base_update_senha_value}}} 
 */
@property(nonatomic) NSString* senha;
/* {{{base_update_nome_base_value}}} 
 */
@property(nonatomic) NSString* nomeBase;
/* {{{base_update_alterado_por_value}}} 
 */
@property(nonatomic) NSString* alteradoPor;
/* {{{base_update_domain_value}}} [optional]
 */
@property(nonatomic) NSString* domain;
/* {{{base_update_senha_criptografada_value}}} 
 */
@property(nonatomic) NSNumber* senhaCriptografada;
/* {{{base_update_nome_base_controle_acesso_value}}} 
 */
@property(nonatomic) NSString* nomeBaseControleAcesso;
/* {{{base_update_id_emissor_value}}} [optional]
 */
@property(nonatomic) NSNumber* idEmissor;
/* {{{base_update_servidor_controle_acesso_value}}} 
 */
@property(nonatomic) NSString* servidorControleAcesso;
/* {{{base_update_nome_base_usuarios_value}}} 
 */
@property(nonatomic) NSString* nomeBaseUsuarios;
/* {{{base_update_servidor_usuarios_value}}} 
 */
@property(nonatomic) NSString* servidorUsuarios;
/* {{{base_update_flag_cluster_value}}} 
 */
@property(nonatomic) NSNumber* flagCluster;

@end
