#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierCartaoResponse.h"


@protocol PierConsultarCartaoResponse
@end

@interface PierConsultarCartaoResponse : PierObject


@property(nonatomic) NSArray<PierCartaoResponse>* cartoes;

@property(nonatomic) NSNumber* codigoRetorno;

@property(nonatomic) NSString* descricaoRetorno;

@end
