#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTipoEnderecoResponse
@end

@interface PierTipoEnderecoResponse : PierObject

/* C\u00F3digo de Identifica\u00E7\u00E3o do Tipo do Endere\u00E7o (id) [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Nome do Tipo do Endere\u00E7o [optional]
 */
@property(nonatomic) NSString* nome;

@end
