#import <Foundation/Foundation.h>
#import "PierTipoFaturamentoResponse.h"
#import "PierTipoFaturamentoPersist.h"
#import "PierTipoFaturamentoPorContaPersist.h"
#import "PierTipoFaturamentoPorContaResponse.h"
#import "PierPageTipoFaturamentoPorContaResponse.h"
#import "PierPageTipoFaturamentoResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierFaturamentoApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierFaturamentoApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierFaturamentoApi*) sharedAPI;
///
///
/// Alterar Faturamento
/// Alterar as configura\u00E7\u00F5es de um determinado tipo de faturamento
///
/// @param _id Id
/// @param tipoFaturamentoPersist tipoFaturamentoPersist
/// 
///
/// @return PierTipoFaturamentoResponse*
-(NSNumber*) alterarTipoFaturamentoUsingPUTWithId: (NSNumber*) _id
    tipoFaturamentoPersist: (PierTipoFaturamentoPersist*) tipoFaturamentoPersist
    completionHandler: (void (^)(PierTipoFaturamentoResponse* output, NSError* error)) handler;


///
///
/// Adiciona uma nova configura\u00E7\u00E3o de faturamento para uma conta
/// Este m\u00E9todo permite adicionar uma nova configura\u00E7\u00E3o de tipo de faturamento para um conta espec\u00EDfica.
///
/// @param tipoFaturamentoPorContaPersist tipoFaturamentoPorContaPersist
/// 
///
/// @return PierTipoFaturamentoPorContaResponse*
-(NSNumber*) cadastrarFaturamentoPorContaUsingPOSTWithTipoFaturamentoPorContaPersist: (PierTipoFaturamentoPorContaPersist*) tipoFaturamentoPorContaPersist
    completionHandler: (void (^)(PierTipoFaturamentoPorContaResponse* output, NSError* error)) handler;


///
///
/// Adiciona um novo faturamento
/// Adiciona uma nova configura\u00E7\u00E3o de tipo de faturamento
///
/// @param tipoFaturamentoPersist tipoFaturamentoPersist
/// 
///
/// @return PierTipoFaturamentoResponse*
-(NSNumber*) cadastrarTipoFaturamentoUsingPOSTWithTipoFaturamentoPersist: (PierTipoFaturamentoPersist*) tipoFaturamentoPersist
    completionHandler: (void (^)(PierTipoFaturamentoResponse* output, NSError* error)) handler;


///
///
/// Consultar Faturamento por id
/// Consulta os detalhes de uma determinada Faturamento
///
/// @param _id Id
/// 
///
/// @return PierTipoFaturamentoResponse*
-(NSNumber*) consultarTipoFaturamentoUsingGETWithId: (NSNumber*) _id
    completionHandler: (void (^)(PierTipoFaturamentoResponse* output, NSError* error)) handler;


///
///
/// Desativar uma configura\u00E7\u00E3o de tipo de faturamento por conta atrav\u00E9s do id
/// Desativa uma configura\u00E7\u00E3o de tipo de faturamento de uma determinada conta.
///
/// @param _id Id
/// @param modificadoPor modificadoPor
/// 
///
/// @return PierTipoFaturamentoPorContaResponse*
-(NSNumber*) desativarFaturamentoPorContaUsingPOSTWithId: (NSNumber*) _id
    modificadoPor: (NSString*) modificadoPor
    completionHandler: (void (^)(PierTipoFaturamentoPorContaResponse* output, NSError* error)) handler;


///
///
/// Desativar uma configura\u00E7\u00E3o de tipo de faturamento atrav\u00E9s do id
/// Desativa uma configura\u00E7\u00E3o de tipo de faturamento.
///
/// @param _id Id
/// 
///
/// @return PierTipoFaturamentoResponse*
-(NSNumber*) desativarTipoFaturamentoUsingPOSTWithId: (NSNumber*) _id
    completionHandler: (void (^)(PierTipoFaturamentoResponse* output, NSError* error)) handler;


///
///
/// Lista as configura\u00E7\u00F5es de tipos de faturamento por conta
/// Este m\u00E9todo permite listar as configura\u00E7\u00F5es de tipos de faturamento registrados a uma conta.
///
/// @param sort Tipo de ordena\u00E7\u00E3o dos registros.
/// @param page P\u00E1gina solicitada (Default = 0)
/// @param limit Limite de elementos por solicita\u00E7\u00E3o (Default = 50, Max = 50)
/// @param idTipoFaturamentoPorConta C\u00F3digo de identifica\u00E7\u00E3o do tipo de faturamento por conta (id).
/// @param status Representa se a configura\u00E7\u00E3o est\u00E1 ativada ou desativada para a conta.
/// @param idConta C\u00F3digo de identifica\u00E7\u00E3o do tipo de faturamento por conta (id).
/// @param idTipoFaturamento C\u00F3digo de identifica\u00E7\u00E3o do tipo de faturamento relacionada (id).
/// @param dataHoraInclusao Data da inclus\u00E3o da configura\u00E7\u00E3o, deve ser informada no formato yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSS&#39;Z&#39;.
/// @param dataHoraCancelamento Data do cancelamento da configura\u00E7\u00E3o, deve ser informada no formato yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSS&#39;Z&#39;.
/// @param modificadoPor Identificador do respons\u00E1vel pela modifica\u00E7\u00E3o do registro.
/// 
///
/// @return PierPageTipoFaturamentoPorContaResponse*
-(NSNumber*) listarFaturamentoPorContaUsingGETWithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    idTipoFaturamentoPorConta: (NSNumber*) idTipoFaturamentoPorConta
    status: (NSNumber*) status
    idConta: (NSNumber*) idConta
    idTipoFaturamento: (NSNumber*) idTipoFaturamento
    dataHoraInclusao: (NSString*) dataHoraInclusao
    dataHoraCancelamento: (NSString*) dataHoraCancelamento
    modificadoPor: (NSString*) modificadoPor
    completionHandler: (void (^)(PierPageTipoFaturamentoPorContaResponse* output, NSError* error)) handler;


///
///
/// Lista Tipos de Faturamento
/// Lista todas as configura\u00E7\u00F5es dos tipos de faturamento
///
/// @param sort Tipo de ordena\u00E7\u00E3o dos registros.
/// @param page P\u00E1gina solicitada (Default = 0)
/// @param limit Limite de elementos por solicita\u00E7\u00E3o (Default = 50, Max = 50)
/// @param idTipoFaturamento C\u00F3digo de identifica\u00E7\u00E3o do tipo de faturamento (id).
/// @param descricao Descri\u00E7\u00E3o do tipo de faturamento.
/// @param flagApenasDemonstrativo Flag que representa que o faturamento ser\u00E1 apenas demonstrativo.
/// @param idConvenio C\u00F3digo de identifica\u00E7\u00E3o do conv\u00EAnio relacionado ao tipo de faturamento.
/// 
///
/// @return PierPageTipoFaturamentoResponse*
-(NSNumber*) listarTipoFaturamentoUsingGETWithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    idTipoFaturamento: (NSNumber*) idTipoFaturamento
    descricao: (NSString*) descricao
    flagApenasDemonstrativo: (NSNumber*) flagApenasDemonstrativo
    idConvenio: (NSNumber*) idConvenio
    completionHandler: (void (^)(PierPageTipoFaturamentoResponse* output, NSError* error)) handler;



@end
