#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierReferenciaIdPersist
@end

@interface PierReferenciaIdPersist : PierObject


@property(nonatomic) NSNumber* _id;

@end
