#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierCartaoDetalhado
@end

@interface PierCartaoDetalhado : PierObject

/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Cart\u00C3\u00A3o (id). [optional]
 */
@property(nonatomic) NSNumber* _id;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Status do Cart\u00C3\u00A3o (id). [optional]
 */
@property(nonatomic) NSNumber* idStatusCartao;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Est\u00C3\u00A1gio de Impress\u00C3\u00A3o do Cart\u00C3\u00A3o (id). [optional]
 */
@property(nonatomic) NSNumber* idEstagioCartao;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o da Conta a qual o cart\u00C3\u00A3o pertence (id). [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o da Pessoa a qual o cart\u00C3\u00A3o pertence (id) [optional]
 */
@property(nonatomic) NSNumber* idPessoa;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Produto a qual o cart\u00C3\u00A3o pertence (id). [optional]
 */
@property(nonatomic) NSNumber* idProduto;
/* Apresenta o tipo do Portador do cart\u00C3\u00A3o, sendo: ('T': Titular, 'A': Adicional). [optional]
 */
@property(nonatomic) NSString* tipoPortador;
/* Apresenta o n\u00C3\u00BAmero do cart\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSString* numeroCartao;
/* Apresenta o nome impresso no cart\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSString* nomeImpresso;
/* Apresenta a data em que o cart\u00C3\u00A3o foi gerado. [optional]
 */
@property(nonatomic) NSString* dataGeracao;
/* Apresenta a data em que o idStatusCartao atual do cart\u00C3\u00A3o fora aplicado, quando houver. [optional]
 */
@property(nonatomic) NSString* dataStatusCartao;
/* Apresenta a data em que o idEstagioCartao atual do cart\u00C3\u00A3o fora aplicado, quando houver. [optional]
 */
@property(nonatomic) NSString* dataEstagioCartao;
/* Apresenta a data de validade do cart\u00C3\u00A3o em formato yyyy-MM, quando houver. [optional]
 */
@property(nonatomic) NSString* dataValidade;
/* Apresenta a data em que o cart\u00C3\u00A3o fora impresso, caso impress\u00C3\u00A3o em loja, ou a data em que ele fora inclu\u00C3\u00ADdo no arquivo para impress\u00C3\u00A3o via gr\u00C3\u00A1fica. [optional]
 */
@property(nonatomic) NSString* dataImpressao;
/* Apresenta o nome do arquivo onde o cart\u00C3\u00A3o fora inclu\u00C3\u00ADdo para impress\u00C3\u00A3o por uma gr\u00C3\u00A1fica, quando houver. [optional]
 */
@property(nonatomic) NSString* arquivoImpressao;
/* Quando ativa, indica que o cart\u00C3\u00A3o fora impresso na Origem Comercial. [optional]
 */
@property(nonatomic) NSNumber* flagImpressaoOrigemComercial;
/* Apresenta o status que informa se o cart\u00C3\u00A3o \u00C3\u00A9 virtual. [optional]
 */
@property(nonatomic) NSNumber* flagVirtual;
/* Apresenta um c\u00C3\u00B3digo espec\u00C3\u00ADfico para ser utilizado como vari\u00C3\u00A1vel no processo de desbloqueio do cart\u00C3\u00A3o para emissores que querem usar esta funcionalidade. [optional]
 */
@property(nonatomic) NSString* codigoDesbloqueio;
/* N\u00C3\u00BAmero sequencial do cart\u00C3\u00A3o [optional]
 */
@property(nonatomic) NSNumber* sequencialCartao;
/* Descreve o tipo do cart\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSString* descricaoTipoCartao;
/* Indica o identificador do tipo do cart\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSNumber* tipoCartao;

@end
