#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierArquivoParametroResponse.h"


@protocol PierArquivoDetalheResponse
@end

@interface PierArquivoDetalheResponse : PierObject

/* C\u00F3digo de identifica\u00E7\u00E3o do arquivo [optional]
 */
@property(nonatomic) NSNumber* _id;
/* C\u00F3digo de identifica\u00E7\u00E3o do Tipo do arquivo [optional]
 */
@property(nonatomic) NSNumber* idTipoArquivo;
/* Descri\u00E7\u00E3o do tipo do arquivo [optional]
 */
@property(nonatomic) NSString* nomeTipoArquivo;
/* Conte\u00FAdo do arquivo convertido em Base 64 [optional]
 */
@property(nonatomic) NSString* arquivo;
/* C\u00F3digo de identifica\u00E7\u00E3o do Status do arquivo [optional]
 */
@property(nonatomic) NSNumber* idStatusArquivo;
/* Desci\u00E7\u00E3o do status do arquivo [optional]
 */
@property(nonatomic) NSString* nomeStatusArquivo;
/* Nome do arquivo [optional]
 */
@property(nonatomic) NSString* nome;
/* Formato/Extens\u00E3o do arquivo [optional]
 */
@property(nonatomic) NSString* extensao;
/* Data de inclus\u00E3o do arquivo. [optional]
 */
@property(nonatomic) NSString* dataInclusao;
/* Data da \u00FAltima altera\u00E7\u00E3o do aquivo. [optional]
 */
@property(nonatomic) NSString* dataAlteracao;
/* Detalhes contendo informa\u00E7\u00F5es adicionais, relacionadas ao arquivo. [optional]
 */
@property(nonatomic) NSArray<PierArquivoParametroResponse>* detalhes;

@end
