#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierContaResponse
@end

@interface PierContaResponse : PierObject

/* {{{conta_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{conta_response_id_produto_value}}} [optional]
 */
@property(nonatomic) NSNumber* idProduto;
/* {{{conta_response_id_origem_comercial_value}}} [optional]
 */
@property(nonatomic) NSNumber* idOrigemComercial;
/* {{{conta_response_id_pessoa_value}}} [optional]
 */
@property(nonatomic) NSNumber* idPessoa;
/* {{{conta_response_id_status_conta_value}}} [optional]
 */
@property(nonatomic) NSNumber* idStatusConta;
/* {{{conta_response_dia_vencimento_value}}} [optional]
 */
@property(nonatomic) NSNumber* diaVencimento;
/* {{{conta_response_melhor_dia_compra_value}}} [optional]
 */
@property(nonatomic) NSNumber* melhorDiaCompra;
/* {{{conta_response_data_status_conta_value}}} [optional]
 */
@property(nonatomic) NSString* dataStatusConta;
/* {{{conta_response_data_cadastro_value}}} [optional]
 */
@property(nonatomic) NSString* dataCadastro;
/* {{{conta_response_data_ultima_alteracao_vencimento_value}}} [optional]
 */
@property(nonatomic) NSString* dataUltimaAlteracaoVencimento;
/* {{{conta_response_valor_renda_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorRenda;

@end
