#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTransferenciaCreditoContaBancariaListaResponse
@end

@interface PierTransferenciaCreditoContaBancariaListaResponse : PierObject

/* C\u00F3digo de identifica\u00E7\u00E3o da transferencia. [optional]
 */
@property(nonatomic) NSNumber* idTransferencia;
/* C\u00F3digo de identifica\u00E7\u00E3o da conta. [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* C\u00F3digo de identifica\u00E7\u00E3o do cart\u00E3o. [optional]
 */
@property(nonatomic) NSNumber* idCartao;
/* Valor da transfer\u00EAncia. [optional]
 */
@property(nonatomic) NSNumber* valorCompra;
/* Valor da transfer\u00EAncia acrescido do valor da tarifa de saque se houver tarifa de saque. [optional]
 */
@property(nonatomic) NSNumber* valorContrato;
/* Data da transfer\u00EAncia. [optional]
 */
@property(nonatomic) NSString* dataCompra;
/* C\u00F3digo de status de processamento. [optional]
 */
@property(nonatomic) NSNumber* status;
/* Status Processamento. [optional]
 */
@property(nonatomic) NSString* statusProcessamento;

@end
