#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierEnderecoResponse
@end

@interface PierEnderecoResponse : PierObject

/* {{{endereco_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{endereco_response_id_pessoa_value}}} [optional]
 */
@property(nonatomic) NSNumber* idPessoa;
/* {{{endereco_response_id_tipo_endereco_value}}} [optional]
 */
@property(nonatomic) NSNumber* idTipoEndereco;
/* {{{endereco_response_cep_value}}} [optional]
 */
@property(nonatomic) NSString* cep;
/* {{{endereco_response_logradouro_value}}} [optional]
 */
@property(nonatomic) NSString* logradouro;
/* {{{endereco_response_numero_value}}} [optional]
 */
@property(nonatomic) NSNumber* numero;
/* {{{endereco_response_complemento_value}}} [optional]
 */
@property(nonatomic) NSString* complemento;
/* {{{endereco_response_ponto_referencia_value}}} [optional]
 */
@property(nonatomic) NSString* pontoReferencia;
/* {{{endereco_response_bairro_value}}} [optional]
 */
@property(nonatomic) NSString* bairro;
/* {{{endereco_response_cidade_value}}} [optional]
 */
@property(nonatomic) NSString* cidade;
/* {{{endereco_response_uf_value}}} [optional]
 */
@property(nonatomic) NSString* uf;
/* {{{endereco_response_pais_value}}} [optional]
 */
@property(nonatomic) NSString* pais;
/* {{{endereco_response_data_inclusao_value}}} [optional]
 */
@property(nonatomic) NSString* dataInclusao;
/* {{{endereco_response_data_ultima_atualizacao_value}}} [optional]
 */
@property(nonatomic) NSString* dataUltimaAtualizacao;
/* {{{endereco_response_flag_correspondencia_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagCorrespondencia;

@end
