#import <Foundation/Foundation.h>
#import "PierTipoTelefone.h"
#import "PierPageTipoTelefones.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierTipoTelefoneApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierTipoTelefoneApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierTipoTelefoneApi*) sharedAPI;
///
///
/// Apresenta os dados de um determinado Tipo de Telefone
/// Este m\u00C3\u00A9todo permite consultar um determinado Tipo de Telefone a partir do seu c\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o (id).
///
/// @param idTipoTelefone C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Tipo do Telefone (id)
/// 
///
/// @return PierTipoTelefone*
-(NSNumber*) consultarUsingGET8WithIdTipoTelefone: (NSNumber*) idTipoTelefone
    completionHandler: (void (^)(PierTipoTelefone* output, NSError* error)) handler;


///
///
/// Lista os Tipos de Telefones
/// Este m\u00C3\u00A9todo permite que sejam listados os Tipos de Telefones existentes na base de dados do Emissor.
///
/// @param _id C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Tipo do Telefone (id).
/// @param nome Nome do Tipo do Telefone
/// @param page P\u00C3\u00A1gina solicitada (Default = 0)
/// @param limit Limite de elementos por solicita\u00C3\u00A7\u00C3\u00A3o (Default = 100, Max = 100)
/// 
///
/// @return PierPageTipoTelefones*
-(NSNumber*) listarUsingGET9WithId: (NSNumber*) _id
    nome: (NSString*) nome
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    completionHandler: (void (^)(PierPageTipoTelefones* output, NSError* error)) handler;



@end
