#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierPlataformaMobilePersistValue_
@end

@interface PierPlataformaMobilePersistValue_ : PierObject

/* {{{plataforma_mobile_persist_nome_value}}} [optional]
 */
@property(nonatomic) NSString* nome;

@end
