#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierBoletoResponse
@end

@interface PierBoletoResponse : PierObject

/* {{{boleto_response_numero_do_documento_value}}} [optional]
 */
@property(nonatomic) NSString* numeroDoDocumento;
/* {{{boleto_response_data_processamento_value}}} [optional]
 */
@property(nonatomic) NSString* dataProcessamento;
/* {{{boleto_response_data_documento_value}}} [optional]
 */
@property(nonatomic) NSString* dataDocumento;
/* {{{boleto_response_data_vencimento_value}}} [optional]
 */
@property(nonatomic) NSString* dataVencimento;
/* {{{boleto_response_data_fechamento_value}}} [optional]
 */
@property(nonatomic) NSString* dataFechamento;
/* {{{boleto_response_valor_boleto_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorBoleto;
/* {{{boleto_response_nome_beneficiario_value}}} [optional]
 */
@property(nonatomic) NSString* nomeBeneficiario;
/* {{{boleto_response_documento_beneficiario_value}}} [optional]
 */
@property(nonatomic) NSString* documentoBeneficiario;
/* {{{boleto_response_agencia_value}}} [optional]
 */
@property(nonatomic) NSString* agencia;
/* {{{boleto_response_codigo_beneficiario_value}}} [optional]
 */
@property(nonatomic) NSString* codigoBeneficiario;
/* {{{boleto_response_numero_convenio_value}}} [optional]
 */
@property(nonatomic) NSString* numeroConvenio;
/* {{{boleto_response_digito_codigo_beneficiario_value}}} [optional]
 */
@property(nonatomic) NSString* digitoCodigoBeneficiario;
/* {{{boleto_response_carteira_value}}} [optional]
 */
@property(nonatomic) NSString* carteira;
/* {{{boleto_response_nosso_numero_value}}} [optional]
 */
@property(nonatomic) NSString* nossoNumero;
/* {{{boleto_response_digito_nosso_numero_value}}} [optional]
 */
@property(nonatomic) NSString* digitoNossoNumero;
/* {{{boleto_response_banco_value}}} [optional]
 */
@property(nonatomic) NSString* banco;
/* {{{boleto_response_aceite_value}}} [optional]
 */
@property(nonatomic) NSNumber* aceite;
/* {{{boleto_response_especie_do_documento_value}}} [optional]
 */
@property(nonatomic) NSString* especieDoDocumento;
/* {{{boleto_response_especie_value}}} [optional]
 */
@property(nonatomic) NSString* especie;
/* {{{boleto_response_instrucoes_value}}} [optional]
 */
@property(nonatomic) NSArray* /* NSString */ instrucoes;
/* {{{boleto_response_locais_de_pagamento_value}}} [optional]
 */
@property(nonatomic) NSArray* /* NSString */ locaisDePagamento;
/* {{{boleto_response_nome_pagador_value}}} [optional]
 */
@property(nonatomic) NSString* nomePagador;
/* {{{boleto_response_documento_pagador_value}}} [optional]
 */
@property(nonatomic) NSString* documentoPagador;
/* {{{boleto_response_logradouro_pagador_value}}} [optional]
 */
@property(nonatomic) NSString* logradouroPagador;
/* {{{boleto_response_bairro_pagador_value}}} [optional]
 */
@property(nonatomic) NSString* bairroPagador;
/* {{{boleto_response_cep_pagador_value}}} [optional]
 */
@property(nonatomic) NSString* cepPagador;
/* {{{boleto_response_cidade_pagador_value}}} [optional]
 */
@property(nonatomic) NSString* cidadePagador;
/* {{{boleto_response_uf_pagador_value}}} [optional]
 */
@property(nonatomic) NSString* ufPagador;
/* {{{boleto_response_codigo_de_barras_value}}} [optional]
 */
@property(nonatomic) NSString* codigoDeBarras;
/* {{{boleto_response_linha_digitavel_value}}} [optional]
 */
@property(nonatomic) NSString* linhaDigitavel;
/* {{{boleto_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{boleto_response_id_conta_value}}} [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* {{{boleto_response_endereco_cobranca_beneficiario_value}}} [optional]
 */
@property(nonatomic) NSString* enderecoCobrancaBeneficiario;
/* {{{boleto_response_status_value}}} [optional]
 */
@property(nonatomic) NSNumber* status;
/* {{{boleto_response_registrado_value}}} [optional]
 */
@property(nonatomic) NSNumber* boletoRegistrado;

@end
