#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierCartaoPayPersist
@end

@interface PierCartaoPayPersist : PierObject

/* N\u00C3\u00BAmero do cart\u00C3\u00A3o criptografado 
 */
@property(nonatomic) NSString* numeroCartao;
/* Data de validade do cart\u00C3\u00A3o [optional]
 */
@property(nonatomic) NSString* dataValidade;
/* CVV do cart\u00C3\u00A3o criptografado [optional]
 */
@property(nonatomic) NSString* cvv;
/* CPF do portador do cart\u00C3\u00A3o criptografado [optional]
 */
@property(nonatomic) NSString* numeroReceitaFederal;
/* Nome impresso no cart\u00C3\u00A3o criptografado [optional]
 */
@property(nonatomic) NSString* nomeImpresso;
/* Chave p\u00C3\u00BAblica do dispositivo criptografada 
 */
@property(nonatomic) NSString* chavePublicaDevice;

@end
