#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTipoFaturamentoResponse
@end

@interface PierTipoFaturamentoResponse : PierObject

/* {{{tipo_faturamento_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{tipo_faturamento_response_descricao_value}}} [optional]
 */
@property(nonatomic) NSString* descricao;
/* {{{tipo_faturamento_response_flag_apenas_demonstrativo_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagApenasDemonstrativo;
/* {{{tipo_faturamento_response_id_convenio_value}}} [optional]
 */
@property(nonatomic) NSNumber* idConvenio;

@end
