#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierContaBancariaPortadorResponse
@end

@interface PierContaBancariaPortadorResponse : PierObject

/* {{{conta_bancaria_portador_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{conta_bancaria_portador_response_id_conta_value}}} [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* {{{conta_bancaria_portador_response_nome_agencia_value}}} [optional]
 */
@property(nonatomic) NSString* nomeAgencia;
/* {{{conta_bancaria_portador_response_banco_value}}} [optional]
 */
@property(nonatomic) NSNumber* banco;
/* {{{conta_bancaria_portador_response_numero_agencia_value}}} [optional]
 */
@property(nonatomic) NSString* numeroAgencia;
/* {{{conta_bancaria_portador_response_digito_agencia_value}}} [optional]
 */
@property(nonatomic) NSString* digitoAgencia;
/* {{{conta_bancaria_portador_response_numero_conta_value}}} [optional]
 */
@property(nonatomic) NSString* numeroConta;
/* {{{conta_bancaria_portador_response_digito_conta_value}}} [optional]
 */
@property(nonatomic) NSString* digitoConta;
/* {{{conta_bancaria_portador_response_flag_ativo_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagAtivo;
/* {{{conta_bancaria_portador_response_flag_conta_origem_doc_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagContaOrigemDoc;
/* {{{conta_bancaria_portador_response_id_pessoa_fisica_value}}} [optional]
 */
@property(nonatomic) NSNumber* idPessoaFisica;
/* {{{conta_bancaria_portador_response_flag_conta_poupanca_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagContaPoupanca;
/* {{{conta_bancaria_portador_response_favorecido_value}}} [optional]
 */
@property(nonatomic) NSString* favorecido;
/* {{{conta_bancaria_portador_response_numero_receira_federal_value}}} [optional]
 */
@property(nonatomic) NSString* numeroReceiraFederal;
/* {{{conta_bancaria_portador_response_titularidade_value}}} [optional]
 */
@property(nonatomic) NSNumber* titularidade;

@end
