#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierAcordoResponse
@end

@interface PierAcordoResponse : PierObject

/* {{{acordo_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{acordo_response_id_conta_value}}} [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* {{{acordo_response_status_acordo_value}}} [optional]
 */
@property(nonatomic) NSNumber* statusAcordo;
/* {{{acordo_response_valor_acordo_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorAcordo;
/* {{{acordo_response_data_acordo_value}}} [optional]
 */
@property(nonatomic) NSString* dataAcordo;
/* {{{acordo_response_quantidade_parcelas_value}}} [optional]
 */
@property(nonatomic) NSNumber* quantidadeParcelas;
/* {{{acordo_response_saldo_atual_final_value}}} [optional]
 */
@property(nonatomic) NSNumber* saldoAtualFinal;
/* {{{acordo_response_dias_em_atraso_value}}} [optional]
 */
@property(nonatomic) NSNumber* diasEmAtraso;

@end
