#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierParametroEmissorResponse
@end

@interface PierParametroEmissorResponse : PierObject

/* {{{parametro_emissor_resposta_codigo_descricao}}} [optional]
 */
@property(nonatomic) NSString* codigo;
/* {{{parametro_emissor_resposta_data_validade_descricao}}} [optional]
 */
@property(nonatomic) NSString* dataValidade;
/* {{{parametro_emissor_resposta_descricao_descricao}}} [optional]
 */
@property(nonatomic) NSString* descricao;
/* {{{parametro_emissor_resposta_tipo_descricao}}} [optional]
 */
@property(nonatomic) NSString* tipo;
/* {{{parametro_emissor_resposta_valor_parametro_descricao}}} [optional]
 */
@property(nonatomic) NSString* valorParametro;

@end
