#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierRefenciaComercialAprovadoPersist
@end

@interface PierRefenciaComercialAprovadoPersist : PierObject

/* Apresenta o nome completo da raz\u00C3\u00A3o social da refer\u00C3\u00AAncia comercial (nome empresarial) [optional]
 */
@property(nonatomic) NSString* razaoSocial;
/* Nome do respons\u00C3\u00A1vel pela refer\u00C3\u00AAncia comercial [optional]
 */
@property(nonatomic) NSString* nomeContrato;
/* DDD do contato da refer\u00C3\u00AAncia comercial [optional]
 */
@property(nonatomic) NSString* ddd;
/* N\u00C3\u00BAmero de contato da refer\u00C3\u00AAncia comercial [optional]
 */
@property(nonatomic) NSString* telefone;
/* E-mail de contato da refer\u00C3\u00AAncia comercial [optional]
 */
@property(nonatomic) NSString* email;

@end
