#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierAlterarProdutoRequest
@end

@interface PierAlterarProdutoRequest : PierObject

/* C\u00C3\u00B3digo identificador do produto. 
 */
@property(nonatomic) NSNumber* idProduto;
/* C\u00C3\u00B3digo identificador da origem comercial. [optional]
 */
@property(nonatomic) NSNumber* idOrigemComercial;
/* Valor do novo limite Global. [optional]
 */
@property(nonatomic) NSNumber* limiteGlobal;

@end
