#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierWebHook
@end

@interface PierWebHook : PierObject

/* Evento a ser chamado pelo WebHook 
 */
@property(nonatomic) NSString* evento;
/* Id do WebHook 
 */
@property(nonatomic) NSNumber* _id;
/* M\u00C3\u00A9todo que a ser chamado pelo WebHook 
 */
@property(nonatomic) NSString* metodo;
/* URL que a ser consumida pelo WebHook 
 */
@property(nonatomic) NSString* url;

@end
