#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierUsuarioTokenResponse
@end

@interface PierUsuarioTokenResponse : PierObject

/* {{{usuario_token_resposta_ativo_descricao}}} [optional]
 */
@property(nonatomic) NSNumber* ativo;
/* {{{usuario_token_resposta_cpf_descricao}}} [optional]
 */
@property(nonatomic) NSString* cpf;
/* {{{usuario_token_resposta_data_inclusao_descricao}}} [optional]
 */
@property(nonatomic) NSString* dataInclusao;
/* {{{usuario_token_resposta_data_nascimento_descricao}}} [optional]
 */
@property(nonatomic) NSString* dataNascimento;
/* {{{usuario_token_resposta_ddd_descricao}}} [optional]
 */
@property(nonatomic) NSString* ddd;
/* {{{usuario_token_resposta_email_descricao}}} [optional]
 */
@property(nonatomic) NSString* email;
/* {{{usuario_token_resposta_telefone_descricao}}} [optional]
 */
@property(nonatomic) NSString* telefone;
/* {{{usuario_token_resposta_token_descricao}}} [optional]
 */
@property(nonatomic) NSString* token;
/* {{{usuario_token_resposta_validade_descricao}}} [optional]
 */
@property(nonatomic) NSString* validade;

@end
