#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierConsultaCadastroEstabelecimentoDTO
@end

@interface PierConsultaCadastroEstabelecimentoDTO : PierObject

/* {{{consulta_cadastro_estabelecimento_d_t_o_data_hora_consulta_value}}} [optional]
 */
@property(nonatomic) NSString* dataHoraConsulta;
/* {{{consulta_cadastro_estabelecimento_d_t_o_status_value}}} [optional]
 */
@property(nonatomic) NSString* status;
/* {{{consulta_cadastro_estabelecimento_d_t_o_tipo_entidade_value}}} [optional]
 */
@property(nonatomic) NSString* tipoEntidade;

@end
