#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierDocumentoTemplateResponse
@end

@interface PierDocumentoTemplateResponse : PierObject

/* {{{documento_template_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{documento_template_response_id_tipo_template_value}}} [optional]
 */
@property(nonatomic) NSNumber* idTipoTemplate;

@end
