#import <Foundation/Foundation.h>
#import "PierContaDebitoRecorrentePersistValue_.h"
#import "PierContaDebitoRecorrenteResponse.h"
#import "PierPageContaDebitoRecorrenteResponse.h"
#import "PierPageTipoDebitoRecorrenteResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierGlobaltagdebitorecorrenteApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierGlobaltagdebitorecorrenteApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierGlobaltagdebitorecorrenteApi*) sharedAPI;
///
///
/// {{{conta_debito_recorrente_resource_aderir}}}
/// {{{conta_debito_recorrente_resource_aderir_notes}}}
///
/// @param contaDebitoRecorrentePersist contaDebitoRecorrentePersist
/// 
///
/// @return PierContaDebitoRecorrenteResponse*
-(NSNumber*) aderirDebitoRecorrenteUsingPOSTWithContaDebitoRecorrentePersist: (PierContaDebitoRecorrentePersistValue_*) contaDebitoRecorrentePersist
    completionHandler: (void (^)(PierContaDebitoRecorrenteResponse* output, NSError* error)) handler;


///
///
/// {{{conta_debito_recorrente_resource_cancelar}}}
/// {{{conta_debito_recorrente_resource_cancelar_notes}}}
///
/// @param _id {{{conta_debito_recorrente_resource_cancelar_param_id_debito_recorrente}}}
/// @param contaDebitoRecorrentePersist contaDebitoRecorrentePersist
/// 
///
/// @return PierContaDebitoRecorrenteResponse*
-(NSNumber*) cancelarDebitoRecorrenteUsingPOSTWithId: (NSNumber*) _id
    contaDebitoRecorrentePersist: (PierContaDebitoRecorrentePersistValue_*) contaDebitoRecorrentePersist
    completionHandler: (void (^)(PierContaDebitoRecorrenteResponse* output, NSError* error)) handler;


///
///
/// {{{conta_debito_recorrente_resource_listar}}}
/// {{{conta_debito_recorrente_resource_listar_notes}}}
///
/// @param idConta {{{conta_debito_recorrente_resource_listar_param_id_conta}}}
/// @param idTipoDebitoRecorrente {{{conta_debito_recorrente_resource_listar_param_id_tipo_debito_recorrente}}}
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param dataHoraInicio {{{conta_debito_recorrente_request_data_hora_inicio_value}}}
/// @param dataHoraFim {{{conta_debito_recorrente_request_data_hora_fim_value}}}
/// @param ativo {{{conta_debito_recorrente_request_ativo_value}}}
/// @param dataHoraUltimoPagamento {{{conta_debito_recorrente_request_data_hora_ultimo_pagamento_value}}}
/// 
///
/// @return PierPageContaDebitoRecorrenteResponse*
-(NSNumber*) listarUsingGET17WithIdConta: (NSNumber*) idConta
    idTipoDebitoRecorrente: (NSNumber*) idTipoDebitoRecorrente
    sort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    dataHoraInicio: (NSString*) dataHoraInicio
    dataHoraFim: (NSString*) dataHoraFim
    ativo: (NSNumber*) ativo
    dataHoraUltimoPagamento: (NSString*) dataHoraUltimoPagamento
    completionHandler: (void (^)(PierPageContaDebitoRecorrenteResponse* output, NSError* error)) handler;


///
///
/// {{{tipo_debito_recorrente_resource_listar}}}
/// {{{tipo_debito_recorrente_resource_listar_notes}}}
///
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param _id {{{tipo_debito_recorrente_request_id_value}}}
/// @param descricao {{{tipo_debito_recorrente_request_descricao_value}}}
/// @param valor {{{tipo_debito_recorrente_request_valor_value}}}
/// @param flagAtivo {{{tipo_debito_recorrente_request_flag_ativo_value}}}
/// 
///
/// @return PierPageTipoDebitoRecorrenteResponse*
-(NSNumber*) listarUsingGET53WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    _id: (NSNumber*) _id
    descricao: (NSString*) descricao
    valor: (NSNumber*) valor
    flagAtivo: (NSNumber*) flagAtivo
    completionHandler: (void (^)(PierPageTipoDebitoRecorrenteResponse* output, NSError* error)) handler;



@end
