#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierPlanoCampanhaUpdate
@end

@interface PierPlanoCampanhaUpdate : PierObject

/* C\u00F3digo identificador do plano campanha [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Quantidade de parcelas [optional]
 */
@property(nonatomic) NSNumber* parcelas;
/* Taxa de juros [optional]
 */
@property(nonatomic) NSNumber* taxa;
/* Nome do usu\u00E1rio [optional]
 */
@property(nonatomic) NSString* usuario;

@end
