#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierEnderecoAprovadoResponse.h"
#import "PierReferenciaComercialAprovadoResponse.h"
#import "PierSocioAprovadoResponse.h"
#import "PierTelefonePessoaAprovadaResponse.h"


@protocol PierPessoaJuridicaAprovadaResponse
@end

@interface PierPessoaJuridicaAprovadaResponse : PierObject

/* C\u00F3digo de Identifica\u00E7\u00E3o da pessoa jur\u00EDdica (id) [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Apresenta o nome completo da raz\u00E3o social (nome empresarial)'. [optional]
 */
@property(nonatomic) NSString* razaoSocial;
/* Apresenta o nome fantasia da empresa. [optional]
 */
@property(nonatomic) NSString* nomeFantasia;
/* N\u00FAmero do Cadastro Nacional de Pessoa Juridica (CNPJ) [optional]
 */
@property(nonatomic) NSString* cnpj;
/* N\u00FAmero da Inscri\u00E7\u00E3o Estadual (IE). [optional]
 */
@property(nonatomic) NSString* inscricaoEstadual;
/* Data de abertura da empresa, essa data deve ser informada no formato: aaaa-MM-dd. [optional]
 */
@property(nonatomic) NSString* dataAberturaEmpresa;
/* Id da origem comercial [optional]
 */
@property(nonatomic) NSNumber* idOrigemComercial;
/* Id do produto [optional]
 */
@property(nonatomic) NSNumber* idProduto;
/* N\u00FAmero da ag\u00EAncia. [optional]
 */
@property(nonatomic) NSNumber* numeroAgencia;
/* N\u00FAmero da conta corrente. [optional]
 */
@property(nonatomic) NSString* numeroContaCorrente;
/* Email da empresa [optional]
 */
@property(nonatomic) NSString* email;
/* Dia vencimento [optional]
 */
@property(nonatomic) NSNumber* diaVencimento;
/* Nome que deve ser impresso no cart\u00E3o [optional]
 */
@property(nonatomic) NSString* nomeImpresso;
/* C\u00F3digo de identifica\u00E7\u00E3o da conta cadastrada [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* C\u00F3digo de identifica\u00E7\u00E3o da proposta [optional]
 */
@property(nonatomic) NSNumber* idProposta;
/* Indica o canal pelo qual o cadastro do cliente foi realizado [optional]
 */
@property(nonatomic) NSString* canalEntrada;
/* Indica o valor da pontua\u00E7\u00E3o atribuido ao cliente (caso n\u00E3o informado ser\u00E1 atribuido o valor = 0) [optional]
 */
@property(nonatomic) NSNumber* valorPontuacao;
/* Apresenta os telefones da empresa [optional]
 */
@property(nonatomic) NSArray<PierTelefonePessoaAprovadaResponse>* telefones;
/* Pode ser informado os seguintes tipos de endere\u00E7o: Residencial, Comercial, e Outros [optional]
 */
@property(nonatomic) NSArray<PierEnderecoAprovadoResponse>* enderecos;
/* Apresenta os dados dos s\u00F3cios da empresa, caso exista [optional]
 */
@property(nonatomic) NSArray<PierSocioAprovadoResponse>* socios;
/* Apresenta os dados dos s\u00F3cios da empresa, caso exista [optional]
 */
@property(nonatomic) NSArray<PierReferenciaComercialAprovadoResponse>* referencias;
/* Valor do Limite Global 
 */
@property(nonatomic) NSNumber* limiteGlobal;
/* Valor m\u00E1ximo do limite de cr\u00E9dito para realizar transa\u00E7\u00F5es 
 */
@property(nonatomic) NSNumber* limiteMaximo;
/* Valor do limite de cr\u00E9dito acumulado da soma das parcelas das compras 
 */
@property(nonatomic) NSNumber* limiteParcelas;

@end
