#import <Foundation/Foundation.h>
#import "PierAlterarProdutoRequest.h"
#import "PierEmprestimoPessoalRequest.h"
#import "PierEmprestimoPessoalResponse.h"
#import "PierByteArray.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierMockApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierMockApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierMockApi*) sharedAPI;
///
///
/// Altera o produto associado \u00C3\u00A0 conta.
/// O recurso permite fazer modifica\u00C3\u00A7\u00C3\u00A3o do produto associado \u00C3\u00A0 conta.
///
/// @param _id C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da conta (id).
/// @param request request
/// 
///
/// @return NSObject*
-(NSNumber*) alterarProdutoUsingPOSTWithId: (NSNumber*) _id
    request: (PierAlterarProdutoRequest*) request
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


///
///
/// Envia 2\u00C2\u00AA via de fatura por E-mail
/// Envia a segunda via da fatura para o e-mail informado/cadastrado.
///
/// @param _id C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da conta (id).
/// @param dataVencimento Data de Vencimento da fatura.
/// @param email E-mail para envio da 2\u00C2\u00AA via da fatura, caso n\u00C3\u00A3o seja informado ser\u00C3\u00A1 usado o e-mail cadastrado.
/// 
///
/// @return NSObject*
-(NSNumber*) enviarFaturaEmailUsingPOSTWithId: (NSNumber*) _id
    dataVencimento: (NSString*) dataVencimento
    email: (NSString*) email
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


///
///
/// Simula valores de presta\u00C3\u00A7\u00C3\u00B5es de empr\u00C3\u00A9stimos/financiamentos
/// Esta opera\u00C3\u00A7\u00C3\u00A3o pode ser utilizada para simular opera\u00C3\u00A7\u00C3\u00B5es financeiras a partir de informa\u00C3\u00A7\u00C3\u00B5es fornecidas pelo usu\u00C3\u00A1rio. Os c\u00C3\u00A1lculos gerados devem ser considerados apenas como refer\u00C3\u00AAncia para as situa\u00C3\u00A7\u00C3\u00B5es reais e n\u00C3\u00A3o como valores oficiais.
///
/// @param request request
/// 
///
/// @return PierEmprestimoPessoalResponse*
-(NSNumber*) simularEmprestimoFinanciamentoUsingPOSTWithRequest: (PierEmprestimoPessoalRequest*) request
    completionHandler: (void (^)(PierEmprestimoPessoalResponse* output, NSError* error)) handler;


///
///
/// Permite visualizar o extrato da fatura em formato PDF
/// Esta opera\u00C3\u00A7\u00C3\u00A3o permite visualizar o extrato da fatura de uma determinada conta, em formato PDF. Quando ela for a fatura ativa, ou seja, a do m\u00C3\u00AAs corrente, o pdf ser\u00C3\u00A1 composto pelo extrato de lan\u00C3\u00A7amentos e pela ficha de compensa\u00C3\u00A7\u00C3\u00A3o banc\u00C3\u00A1ria. Quando for de uma fatura do hist\u00C3\u00B3rico do cliente, o PDF ser\u00C3\u00A1 composto apenas pelo extrato de transa\u00C3\u00A7\u00C3\u00B5es.
///
/// @param _id C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da conta (id).
/// @param dataVencimento Data de Vencimento da fatura.
/// 
///
/// @return NSArray<PierByteArray>*
-(NSNumber*) visualizarDocumentoUsingPOSTWithId: (NSNumber*) _id
    dataVencimento: (NSString*) dataVencimento
    completionHandler: (void (^)(NSArray<PierByteArray>* output, NSError* error)) handler;



@end
