#import <Foundation/Foundation.h>
#import "PierAntecipacaoResponse.h"
#import "PierPageCompras.h"
#import "PierAntecipacaoSimuladaResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierCompraApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierCompraApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierCompraApi*) sharedAPI;
///
///
/// Faz a efetiva\u00C3\u00A7\u00C3\u00A3o da antecipa\u00C3\u00A7\u00C3\u00A3o
/// Metodo responsavel pela efetiva\u00C3\u00A7\u00C3\u00A3o da antecipa\u00C3\u00A7\u00C3\u00A3o.
///
/// @param idConta C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o da Conta.
/// @param _id C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o da compra.
/// @param quantidadeParcelas Quantidade de parcelas para serem antecipadas (quantidadeParcelas).
/// 
///
/// @return PierAntecipacaoResponse*
-(NSNumber*) efetivarAntecipacaoUsingPOSTWithIdConta: (NSNumber*) idConta
    _id: (NSNumber*) _id
    quantidadeParcelas: (NSNumber*) quantidadeParcelas
    completionHandler: (void (^)(PierAntecipacaoResponse* output, NSError* error)) handler;


///
///
/// Listar compras
/// Lista as compras de uma conta.
///
/// @param idConta C\u00C3\u00B3digo identificador da conta da Compra.
/// @param page P\u00C3\u00A1gina solicitada (Default = 0)
/// @param limit Limite de elementos por solicita\u00C3\u00A7\u00C3\u00A3o (Default = 50, Max = 50)
/// @param idCompra C\u00C3\u00B3digo identificador da Compra.
/// @param parcelada Indica se a compra \u00C3\u00A9 parcelada.
/// @param juros Indica se a compra \u00C3\u00A9 com ou sem juros.
/// @param tipoTransacao Indica se a compra \u00C3\u00A9 ON-US ou OFF-US
/// 
///
/// @return PierPageCompras*
-(NSNumber*) listarUsingGET5WithIdConta: (NSNumber*) idConta
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    idCompra: (NSNumber*) idCompra
    parcelada: (NSNumber*) parcelada
    juros: (NSNumber*) juros
    tipoTransacao: (NSString*) tipoTransacao
    completionHandler: (void (^)(PierPageCompras* output, NSError* error)) handler;


///
///
/// Simular antecipa\u00C3\u00A7\u00C3\u00A3o de parcelas
/// Simula a antecipa\u00C3\u00A7\u00C3\u00A3o de parcelas de uma compra, listando todos os planos de parcelamento dispon\u00C3\u00ADveis.
///
/// @param idConta C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da conta (id).
/// @param _id C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o da compra.
/// 
///
/// @return PierAntecipacaoSimuladaResponse*
-(NSNumber*) simularAntecipacaoUsingGETWithIdConta: (NSNumber*) idConta
    _id: (NSNumber*) _id
    completionHandler: (void (^)(PierAntecipacaoSimuladaResponse* output, NSError* error)) handler;



@end
