#import <Foundation/Foundation.h>
#import "PierPageGrupoChargebackResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierGlobaltagcompracontestadaApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierGlobaltagcompracontestadaApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierGlobaltagcompracontestadaApi*) sharedAPI;
///
///
/// {{{compra_contestada_detalhe_cartao_resource_listar}}}
/// {{{compra_contestada_detalhe_cartao_resource_listar_notes}}}
///
/// @param idCartao idCartao
/// 
///
/// @return PierPageGrupoChargebackResponse*
-(NSNumber*) detalheCartaoUsingGETWithIdCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(PierPageGrupoChargebackResponse* output, NSError* error)) handler;


///
///
/// {{{cartao_com_compra_contestada_resource_listar}}}
/// {{{cartao_com_compra_contestada_resource_listar_notes}}}
///
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// 
///
/// @return PierPageGrupoChargebackResponse*
-(NSNumber*) listarUsingGET12WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    completionHandler: (void (^)(PierPageGrupoChargebackResponse* output, NSError* error)) handler;


///
///
/// {{{compra_contestada_transacoes_resource_listar}}}
/// {{{compra_contestada_transacoes_resource_listar_notes}}}
///
/// @param idCartao idCartao
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// 
///
/// @return PierPageGrupoChargebackResponse*
-(NSNumber*) transacaoUsingGETWithIdCartao: (NSNumber*) idCartao
    sort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    completionHandler: (void (^)(PierPageGrupoChargebackResponse* output, NSError* error)) handler;



@end
