#import <Foundation/Foundation.h>
#import "PierWebHookPersistValue_.h"
#import "PierWebHookResponse.h"
#import "PierPageWebHookResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierGlobaltagwebhookApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierGlobaltagwebhookApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierGlobaltagwebhookApi*) sharedAPI;
///
///
/// {{{web_hook_resource_alterar}}}
/// {{{web_hook_resource_alterar_notes}}}
///
/// @param _id {{{web_hook_resource_alterar_param_id}}}
/// @param webhook webhook
/// @param status {{{web_hook_resource_alterar_param_status}}}
/// 
///
/// @return PierWebHookResponse*
-(NSNumber*) alterarUsingPUT24WithId: (NSNumber*) _id
    webhook: (PierWebHookPersistValue_*) webhook
    status: (NSString*) status
    completionHandler: (void (^)(PierWebHookResponse* output, NSError* error)) handler;


///
///
/// {{{web_hook_resource_consultar}}}
/// {{{web_hook_resource_consultar_notes}}}
///
/// @param _id {{{web_hook_resource_consultar_param_id}}}
/// 
///
/// @return PierWebHookResponse*
-(NSNumber*) consultarUsingGET55WithId: (NSNumber*) _id
    completionHandler: (void (^)(PierWebHookResponse* output, NSError* error)) handler;


///
///
/// {{{web_hook_resource_listar}}}
/// {{{web_hook_resource_listar_notes}}}
///
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param _id {{{web_hook_request_id_value}}}
/// @param tipoEvento {{{web_hook_request_tipo_evento_value}}}
/// @param metodo {{{web_hook_request_metodo_value}}}
/// @param url {{{web_hook_request_url_value}}}
/// 
///
/// @return PierPageWebHookResponse*
-(NSNumber*) listarUsingGET69WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    _id: (NSNumber*) _id
    tipoEvento: (NSString*) tipoEvento
    metodo: (NSString*) metodo
    url: (NSString*) url
    completionHandler: (void (^)(PierPageWebHookResponse* output, NSError* error)) handler;


///
///
/// {{{web_hook_resource_salvar}}}
/// {{{web_hook_resource_salvar_notes}}}
///
/// @param webhook webhook
/// 
///
/// @return PierWebHookResponse*
-(NSNumber*) salvarUsingPOST36WithWebhook: (PierWebHookPersistValue_*) webhook
    completionHandler: (void (^)(PierWebHookResponse* output, NSError* error)) handler;



@end
