#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierArquivoParametroResponse.h"


@protocol PierArquivoDetalheResponse
@end

@interface PierArquivoDetalheResponse : PierObject

/* {{{arquivo_detalhe_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{arquivo_detalhe_response_id_tipo_arquivo_value}}} [optional]
 */
@property(nonatomic) NSNumber* idTipoArquivo;
/* {{{arquivo_detalhe_response_nome_tipo_arquivo_value}}} [optional]
 */
@property(nonatomic) NSString* nomeTipoArquivo;
/* {{{arquivo_detalhe_response_arquivo_value}}} [optional]
 */
@property(nonatomic) NSString* arquivo;
/* {{{arquivo_detalhe_response_id_status_arquivo_value}}} [optional]
 */
@property(nonatomic) NSNumber* idStatusArquivo;
/* {{{arquivo_detalhe_response_nome_status_arquivo_value}}} [optional]
 */
@property(nonatomic) NSString* nomeStatusArquivo;
/* {{{arquivo_detalhe_response_nome_value}}} [optional]
 */
@property(nonatomic) NSString* nome;
/* {{{arquivo_detalhe_response_extensao_value}}} [optional]
 */
@property(nonatomic) NSString* extensao;
/* {{{arquivo_detalhe_response_data_inclusao_value}}} [optional]
 */
@property(nonatomic) NSString* dataInclusao;
/* {{{arquivo_detalhe_response_data_alteracao_value}}} [optional]
 */
@property(nonatomic) NSString* dataAlteracao;
/* {{{arquivo_detalhe_response_detalhes_value}}} [optional]
 */
@property(nonatomic) NSArray<PierArquivoParametroResponse>* detalhes;

@end
