#import <Foundation/Foundation.h>
#import "PierBoletoResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierBoletoApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierBoletoApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierBoletoApi*) sharedAPI;
///
///
/// Registra uma cobranca na entidade banco relacionada a cobranca informado.
/// Este recurso registra uma cobranca emitido.
///
/// @param _id C\u00F3digo de Identifica\u00E7\u00E3o da Cobranca (id)
/// 
///
/// @return PierBoletoResponse*
-(NSNumber*) registrarBoletoUsingPOSTWithId: (NSNumber*) _id
    completionHandler: (void (^)(PierBoletoResponse* output, NSError* error)) handler;



@end
