#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierNotificacaoEmailResponse
@end

@interface PierNotificacaoEmailResponse : PierObject

/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da notifica\u00C3\u00A7\u00C3\u00A3o gerada. [optional]
 */
@property(nonatomic) NSNumber* _id;
/* C\u00C3\u00B3digo identificador do template da notifica\u00C3\u00A7\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSNumber* idTemplateNotificacao;
/* C\u00C3\u00B3digo identificador do Documento. [optional]
 */
@property(nonatomic) NSNumber* idDocumento;
/* Email do destinat\u00C3\u00A1rio da notifica\u00C3\u00A7\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSString* destinatario;
/* Email do remetente da notifica\u00C3\u00A7\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSString* remetente;

@end
