#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierMapOfstringAndstring.h"


@protocol PierTransacaoOnUsResponse
@end

@interface PierTransacaoOnUsResponse : PierObject

/* {{{transacao_on_us_response_nsu_origem_value}}} [optional]
 */
@property(nonatomic) NSString* nsuOrigem;
/* {{{transacao_on_us_response_nsu_autorizacao_value}}} [optional]
 */
@property(nonatomic) NSString* nsuAutorizacao;
/* {{{transacao_on_us_response_plano_de_parcelamento_value}}} [optional]
 */
@property(nonatomic) NSArray<PierMapOfstringAndstring>* planoDeParcelamento;
/* {{{transacao_on_us_response_codigo_autorizacao_value}}} [optional]
 */
@property(nonatomic) NSString* codigoAutorizacao;
/* {{{transacao_on_us_response_numero_mascarado_cartao_value}}} [optional]
 */
@property(nonatomic) NSString* numeroMascaradoCartao;
/* {{{transacao_on_us_response_nome_portador_cartao_value}}} [optional]
 */
@property(nonatomic) NSString* nomePortadorCartao;
/* {{{transacao_on_us_response_terminal_requisitante_value}}} 
 */
@property(nonatomic) NSString* terminalRequisitante;

@end
