#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierAntecipacaoSimuladaDetalhesResponse.h"


@protocol PierAntecipacaoSimuladaResponse
@end

@interface PierAntecipacaoSimuladaResponse : PierObject


@property(nonatomic) NSNumber* mcc;

@property(nonatomic) NSString* uf;
/* {{{antecipacao_simulada_response_id_antecipacao_simulada_value}}} [optional]
 */
@property(nonatomic) NSNumber* idAntecipacaoSimulada;
/* {{{antecipacao_simulada_response_id_conta_value}}} [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* {{{antecipacao_simulada_response_id_compra_value}}} [optional]
 */
@property(nonatomic) NSNumber* idCompra;
/* {{{antecipacao_simulada_response_id_tipo_transacao_value}}} [optional]
 */
@property(nonatomic) NSNumber* idTipoTransacao;
/* {{{antecipacao_simulada_response_quantidade_parcelas_antecipaveis_value}}} [optional]
 */
@property(nonatomic) NSNumber* quantidadeParcelasAntecipaveis;
/* {{{antecipacao_simulada_response_valor_parcela_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorParcela;
/* {{{antecipacao_simulada_response_data_hora_simulacao_value}}} [optional]
 */
@property(nonatomic) NSString* dataHoraSimulacao;
/* {{{antecipacao_simulada_response_taxa_antecipacao_ano_value}}} [optional]
 */
@property(nonatomic) NSNumber* taxaAntecipacaoAno;
/* {{{antecipacao_simulada_response_nome_estabelecimento_value}}} [optional]
 */
@property(nonatomic) NSString* nomeEstabelecimento;
/* {{{antecipacao_simulada_response_status_value}}} [optional]
 */
@property(nonatomic) NSString* status;
/* {{{antecipacao_simulada_response_data_compra_value}}} [optional]
 */
@property(nonatomic) NSString* dataCompra;
/* {{{antecipacao_simulada_response_tipo_origem_transacao_value}}} [optional]
 */
@property(nonatomic) NSString* tipoOrigemTransacao;
/* {{{antecipacao_simulada_response_cidade_value}}} [optional]
 */
@property(nonatomic) NSString* cidade;
/* {{{antecipacao_simulada_response_pais_value}}} [optional]
 */
@property(nonatomic) NSString* pais;
/* {{{antecipacao_simulada_response_latitude_value}}} [optional]
 */
@property(nonatomic) NSString* latitude;
/* {{{antecipacao_simulada_response_longitude_value}}} [optional]
 */
@property(nonatomic) NSString* longitude;
/* {{{antecipacao_simulada_response_id_grupo_m_c_c_value}}} [optional]
 */
@property(nonatomic) NSNumber* idGrupoMCC;
/* {{{antecipacao_simulada_response_descricao_grupo_m_c_c_value}}} [optional]
 */
@property(nonatomic) NSString* descricaoGrupoMCC;
/* {{{antecipacao_simulada_response_id_produto_value}}} [optional]
 */
@property(nonatomic) NSNumber* idProduto;
/* {{{antecipacao_simulada_response_descricao_produto_value}}} [optional]
 */
@property(nonatomic) NSString* descricaoProduto;
/* {{{antecipacao_simulada_response_descricao_estabelecimento_value}}} [optional]
 */
@property(nonatomic) NSString* descricaoEstabelecimento;
/* {{{antecipacao_simulada_response_nome_fantasia_estabelecimento_value}}} [optional]
 */
@property(nonatomic) NSString* nomeFantasiaEstabelecimento;
/* {{{antecipacao_simulada_response_detalhes_value}}} [optional]
 */
@property(nonatomic) NSArray<PierAntecipacaoSimuladaDetalhesResponse>* detalhes;

@end
