#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierTipoTransacaoAjusteResponse.h"


@protocol PierTipoAjusteResponse
@end

@interface PierTipoAjusteResponse : PierObject

/* {{{tipo_ajuste_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{tipo_ajuste_response_descricao_value}}} [optional]
 */
@property(nonatomic) NSString* descricao;
/* {{{tipo_ajuste_response_transacoes_value}}} [optional]
 */
@property(nonatomic) NSArray<PierTipoTransacaoAjusteResponse>* transacoes;

@end
