#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTipoTelefone
@end

@interface PierTipoTelefone : PierObject

/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Tipo do Telefone (id). [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Nome do Tipo do Telefone [optional]
 */
@property(nonatomic) NSString* nome;

@end
