#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierAplicacaoMobileEmissorResponse.h"
#import "PierCartaoEmissorResponse.h"


@protocol PierInscricaoAPNResponse
@end

@interface PierInscricaoAPNResponse : PierObject

/* {{{inscricao_apn_resposta_aplicacao_mobile_descricao}}} [optional]
 */
@property(nonatomic) PierAplicacaoMobileEmissorResponse* aplicacaoMobile;
/* {{{inscricao_apn_resposta_ativo_descricao}}} [optional]
 */
@property(nonatomic) NSNumber* ativo;
/* {{{inscricao_apn_resposta_cartao_descricao}}} [optional]
 */
@property(nonatomic) PierCartaoEmissorResponse* cartao;
/* {{{inscricao_apn_resposta_data_criacao_descricao}}} [optional]
 */
@property(nonatomic) NSString* dataCriacao;
/* {{{inscricao_apn_resposta_data_desativacao_descricao}}} [optional]
 */
@property(nonatomic) NSString* dataDesativacao;
/* {{{inscricao_apn_resposta_device_token_descricao}}} [optional]
 */
@property(nonatomic) NSString* deviceToken;
/* {{{inscricao_apn_resposta_id_descricao}}} [optional]
 */
@property(nonatomic) NSNumber* _id;

@end
