#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierAtribuirAssinaturaClientePersist
@end

@interface PierAtribuirAssinaturaClientePersist : PierObject

/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do Arquivo [optional]
 */
@property(nonatomic) NSNumber* idArquivo;

@end
