#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierNotificacaoPushResponse
@end

@interface PierNotificacaoPushResponse : PierObject

/* Apresenta a data e em que o registro foi enviado para o dispositivo. [optional]
 */
@property(nonatomic) NSDate* dataEnvio;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do emissor (id). [optional]
 */
@property(nonatomic) NSNumber* idEmissor;
/* Nome do evento da notifica\u00C3\u00A7\u00C3\u00A3o [optional]
 */
@property(nonatomic) NSString* evento;
/* Status de envio da notifica\u00C3\u00A7\u00C3\u00A3o [optional]
 */
@property(nonatomic) NSString* status;
/* C\u00C3\u00B3digo identificado da pessoa 
 */
@property(nonatomic) NSNumber* idPessoa;
/* C\u00C3\u00B3digo identificador da conta 
 */
@property(nonatomic) NSNumber* idConta;
/* Token do dispositivo a qual foi destinado a notifica\u00C3\u00A7\u00C3\u00A3o (device_token) 
 */
@property(nonatomic) NSString* tokenDispositivo;
/* T\u00C3\u00ADtulo da notifica\u00C3\u00A7\u00C3\u00A3o enviada. 
 */
@property(nonatomic) NSString* titulo;
/* Conte\u00C3\u00BAdo da notifica\u00C3\u00A7\u00C3\u00A3o enviada. 
 */
@property(nonatomic) NSString* conteudo;
/* Nome do Sistema Operacional a qual foi enviado o Push. [optional]
 */
@property(nonatomic) NSString* plataforma;
/* N\u00C3\u00BAmero do protocolo de envio de notifica\u00C3\u00A7\u00C3\u00B5es [optional]
 */
@property(nonatomic) NSString* protocolo;

@end
