#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierEnderecoAprovadoResponse
@end

@interface PierEnderecoAprovadoResponse : PierObject

/* {{{endereco_aprovado_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{endereco_aprovado_response_id_tipo_endereco_value}}} [optional]
 */
@property(nonatomic) NSNumber* idTipoEndereco;
/* {{{endereco_aprovado_response_cep_value}}} [optional]
 */
@property(nonatomic) NSString* cep;
/* {{{endereco_aprovado_response_logradouro_value}}} [optional]
 */
@property(nonatomic) NSString* logradouro;
/* {{{endereco_aprovado_response_numero_value}}} [optional]
 */
@property(nonatomic) NSNumber* numero;
/* {{{endereco_aprovado_response_complemento_value}}} [optional]
 */
@property(nonatomic) NSString* complemento;
/* {{{endereco_aprovado_response_ponto_referencia_value}}} [optional]
 */
@property(nonatomic) NSString* pontoReferencia;
/* {{{endereco_aprovado_response_bairro_value}}} [optional]
 */
@property(nonatomic) NSString* bairro;
/* {{{endereco_aprovado_response_cidade_value}}} [optional]
 */
@property(nonatomic) NSString* cidade;
/* {{{endereco_aprovado_response_uf_value}}} [optional]
 */
@property(nonatomic) NSString* uf;
/* {{{endereco_aprovado_response_pais_value}}} [optional]
 */
@property(nonatomic) NSString* pais;
/* {{{endereco_aprovado_response_endereco_correspondencia_value}}} [optional]
 */
@property(nonatomic) NSNumber* enderecoCorrespondencia;

@end
