#import <Foundation/Foundation.h>
#import "PierPageCodigoChargebackResponse.h"
#import "PierPageGrupoChargebackResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierGlobaltaggrupochagebackApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierGlobaltaggrupochagebackApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierGlobaltaggrupochagebackApi*) sharedAPI;
///
///
/// {{{codigo_chargeback_resource_listar}}}
/// {{{codigo_chargeback_resource_listar_notes}}}
///
/// @param _id id
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param flagAtm 
/// @param idBandeira 
/// @param groupId 
/// 
///
/// @return PierPageCodigoChargebackResponse*
-(NSNumber*) listarCodigosUsingGETWithId: (NSNumber*) _id
    sort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    flagAtm: (NSNumber*) flagAtm
    idBandeira: (NSNumber*) idBandeira
    groupId: (NSNumber*) groupId
    completionHandler: (void (^)(PierPageCodigoChargebackResponse* output, NSError* error)) handler;


///
///
/// {{{grupo_chargeback_resource_listar}}}
/// {{{grupo_chargeback_resource_listar_notes}}}
///
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// 
///
/// @return PierPageGrupoChargebackResponse*
-(NSNumber*) listarUsingGET27WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    completionHandler: (void (^)(PierPageGrupoChargebackResponse* output, NSError* error)) handler;



@end
