#import <Foundation/Foundation.h>
#import "PierPageSMSEnvioResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierGlobaltagsmsApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierGlobaltagsmsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierGlobaltagsmsApi*) sharedAPI;
///
///
/// {{{sms_resource_listar_sms}}}
/// {{{sms_resource_listar_sms_notes}}}
///
/// @param idConta {{{sms_envio_request_id_conta_value}}}
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param dataInicio {{{sms_envio_request_data_inicio_value}}}
/// @param dataFim {{{sms_envio_request_data_fim_value}}}
/// 
///
/// @return PierPageSMSEnvioResponse*
-(NSNumber*) listarSMSUsingGET1WithIdConta: (NSNumber*) idConta
    sort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    dataInicio: (NSString*) dataInicio
    dataFim: (NSString*) dataFim
    completionHandler: (void (^)(PierPageSMSEnvioResponse* output, NSError* error)) handler;



@end
