#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierValidaCVVRequest
@end

@interface PierValidaCVVRequest : PierObject

/* C\u00F3digo de identifica\u00E7\u00E3o do chave de criptografia. [optional]
 */
@property(nonatomic) NSNumber* idChaveCriptografia;
/* Valor de Verifica\u00E7\u00E3o do Cart\u00E3o (CVV). [optional]
 */
@property(nonatomic) NSString* cvv;

@end
