#import <Foundation/Foundation.h>
#import "PierArquivoDetalheResponse.h"
#import "PierIntegrarArquivoRequest.h"
#import "PierPageArquivoResponse.h"
#import "PierArquivoPersist.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierArquivoApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierArquivoApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierArquivoApi*) sharedAPI;
///
///
/// Consulta de arquivo no PIER Cloud
/// Este recurso permite consultar um determinado arquivo armazenado no PIER Cloud.
///
/// @param _id C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do arquivo
/// 
///
/// @return PierArquivoDetalheResponse*
-(NSNumber*) consultarUsingGET2WithId: (NSNumber*) _id
    completionHandler: (void (^)(PierArquivoDetalheResponse* output, NSError* error)) handler;


///
///
/// Integrar Arquivos
/// Este recurso foi desenvolvido para realizar a integra\u00C3\u00A7\u00C3\u00A3o de arquivos do PIER Cloud junto a reposit\u00C3\u00B3rios externos pr\u00C3\u00A9-configurado.
///
/// @param integrarArquivoRequest integrarArquivoRequest
/// 
///
/// @return NSObject*
-(NSNumber*) integrarUsingPOSTWithIntegrarArquivoRequest: (PierIntegrarArquivoRequest*) integrarArquivoRequest
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


///
///
/// Listar arquivos do Pier Cloud
/// Este recurso permite a listagem de todos os arquivos dispon\u00C3\u00ADveis no Pier Cloud.
///
/// @param sort Tipo de ordena\u00C3\u00A7\u00C3\u00A3o dos registros.
/// @param page P\u00C3\u00A1gina solicitada (Default = 0)
/// @param limit Limite de elementos por solicita\u00C3\u00A7\u00C3\u00A3o (Default = 50, Max = 50)
/// @param nome Nome do arquivo
/// @param idTipoArquivo Tipo do arquivo
/// @param idStatusArquivo Identificador do status do arquivo
/// @param extensao Extens\u00C3\u00A3o do arquivo
/// 
///
/// @return PierPageArquivoResponse*
-(NSNumber*) listarUsingGET3WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    nome: (NSString*) nome
    idTipoArquivo: (NSNumber*) idTipoArquivo
    idStatusArquivo: (NSNumber*) idStatusArquivo
    extensao: (NSString*) extensao
    completionHandler: (void (^)(PierPageArquivoResponse* output, NSError* error)) handler;


///
///
/// Permite armazenar arquivos no PIER Cloud
/// Este recurso permite o armazenamento de arquivos no PIER Cloud.
///
/// @param arquivoPersist arquivoPersist
/// 
///
/// @return PierArquivoDetalheResponse*
-(NSNumber*) salvarUsingPOST1WithArquivoPersist: (PierArquivoPersist*) arquivoPersist
    completionHandler: (void (^)(PierArquivoDetalheResponse* output, NSError* error)) handler;



@end
