#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierConfiguracaoRegistroCobrancaResponse
@end

@interface PierConfiguracaoRegistroCobrancaResponse : PierObject

/* {{{configuracao_registro_cobranca_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{configuracao_registro_cobranca_response_id_emissor_value}}} [optional]
 */
@property(nonatomic) NSNumber* idEmissor;
/* {{{configuracao_registro_cobranca_response_codigo_banco_value}}} [optional]
 */
@property(nonatomic) NSNumber* codigoBanco;
/* {{{configuracao_registro_cobranca_response_uri_value}}} [optional]
 */
@property(nonatomic) NSString* uri;
/* {{{configuracao_registro_cobranca_response_key_store_name_value}}} [optional]
 */
@property(nonatomic) NSString* keyStoreName;
/* {{{configuracao_registro_cobranca_response_key_store_password_value}}} [optional]
 */
@property(nonatomic) NSString* keyStorePassword;
/* {{{configuracao_registro_cobranca_response_keystore_alias_value}}} [optional]
 */
@property(nonatomic) NSString* keystoreAlias;
/* {{{configuracao_registro_cobranca_response_key_store_private_key_password_value}}} [optional]
 */
@property(nonatomic) NSString* keyStorePrivateKeyPassword;
/* {{{configuracao_registro_cobranca_response_type_keystore_value}}} [optional]
 */
@property(nonatomic) NSString* typeKeystore;
/* {{{configuracao_registro_cobranca_response_trust_store_name_value}}} [optional]
 */
@property(nonatomic) NSString* trustStoreName;
/* {{{configuracao_registro_cobranca_response_trust_store_password_value}}} [optional]
 */
@property(nonatomic) NSString* trustStorePassword;
/* {{{configuracao_registro_cobranca_response_truststore_alias_value}}} [optional]
 */
@property(nonatomic) NSString* truststoreAlias;
/* {{{configuracao_registro_cobranca_response_type_truststore_value}}} [optional]
 */
@property(nonatomic) NSString* typeTruststore;
/* {{{configuracao_registro_cobranca_response_uri_adicional_value}}} [optional]
 */
@property(nonatomic) NSString* uriAdicional;
/* {{{configuracao_registro_cobranca_response_status_value}}} [optional]
 */
@property(nonatomic) NSString* status;
/* {{{configuracao_registro_cobranca_persist_secret_value}}} 
 */
@property(nonatomic) NSString* secret;
/* {{{configuracao_registro_cobranca_persist_client_id_value}}} 
 */
@property(nonatomic) NSString* clientID;

@end
