#import <Foundation/Foundation.h>
#import "PierTipoEndereco.h"
#import "PierPageTiposEndereco.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierTipoEnderecoApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierTipoEnderecoApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierTipoEnderecoApi*) sharedAPI;
///
///
/// Apresenta os dados de um determinado Tipo de Endere\u00C3\u00A7o
/// Este m\u00C3\u00A9todo permite consultar um determinado Tipo de Endere\u00C3\u00A7o a partir do seu c\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o (id).
///
/// @param idTipoEndereco C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Tipo do Endere\u00C3\u00A7o (id)
/// 
///
/// @return PierTipoEndereco*
-(NSNumber*) consultarUsingGET7WithIdTipoEndereco: (NSNumber*) idTipoEndereco
    completionHandler: (void (^)(PierTipoEndereco* output, NSError* error)) handler;


///
///
/// Lista as op\u00C3\u00B5es de Tipos de Endere\u00C3\u00A7os do Emissor 
/// Este m\u00C3\u00A9todo permite que sejam listados os Tipos de Endere\u00C3\u00A7os existentes na base de dados do Emissor.
///
/// @param _id C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Tipo do Endere\u00C3\u00A7o (id)
/// @param nome Nome do Tipo do Endere\u00C3\u00A7o
/// @param page P\u00C3\u00A1gina solicitada (Default = 0)
/// @param limit Limite de elementos por solicita\u00C3\u00A7\u00C3\u00A3o (Default = 100, Max = 100)
/// 
///
/// @return PierPageTiposEndereco*
-(NSNumber*) listarUsingGET8WithId: (NSNumber*) _id
    nome: (NSString*) nome
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    completionHandler: (void (^)(PierPageTiposEndereco* output, NSError* error)) handler;



@end
