#import <Foundation/Foundation.h>
#import "PierStatusOportunidadePersistValue_.h"
#import "PierStatusOportunidadeResponse.h"
#import "PierOportunidadeUpdateValue_.h"
#import "PierOportunidadeResponse.h"
#import "PierTipoOportunidadeResponse.h"
#import "PierTipoOportunidadePersistValue_.h"
#import "PierPageStatusOportunidadeAUDResponse.h"
#import "PierPageOportunidadeAUDResponse.h"
#import "PierPageTipoOportunidadeAUDResponse.h"
#import "PierPageStatusOportunidadeResponse.h"
#import "PierPageOportunidadeResponse.h"
#import "PierPageTipoOportunidadeResponse.h"
#import "PierOportunidadePersistValue_.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierGlobaltagoportunidadeApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierGlobaltagoportunidadeApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierGlobaltagoportunidadeApi*) sharedAPI;
///
///
/// {{{tipo_oportunidade_resource_alterar_status}}}
/// {{{tipo_oportunidade_resource_alterar_status_notes}}}
///
/// @param _id {{{tipo_oportunidade_resource_alterar_status_param_id}}}
/// @param idStatus {{{tipo_oportunidade_resource_alterar_status_param_id_status}}}
/// @param persist persist
/// 
///
/// @return PierStatusOportunidadeResponse*
-(NSNumber*) alterarStatusUsingPUTWithId: (NSNumber*) _id
    idStatus: (NSNumber*) idStatus
    persist: (PierStatusOportunidadePersistValue_*) persist
    completionHandler: (void (^)(PierStatusOportunidadeResponse* output, NSError* error)) handler;


///
///
/// {{{oportunidade_resource_alterar}}}
/// {{{oportunidade_resource_alterar_notes}}}
///
/// @param _id {{{oportunidade_resource_alterar_param_id}}}
/// @param update update
/// 
///
/// @return PierOportunidadeResponse*
-(NSNumber*) alterarUsingPUT12WithId: (NSNumber*) _id
    update: (PierOportunidadeUpdateValue_*) update
    completionHandler: (void (^)(PierOportunidadeResponse* output, NSError* error)) handler;


///
///
/// {{{tipo_oportunidade_resource_alterar}}}
/// {{{tipo_oportunidade_resource_alterar_notes}}}
///
/// @param _id {{{tipo_oportunidade_resource_alterar_param_id}}}
/// @param persist persist
/// 
///
/// @return PierTipoOportunidadeResponse*
-(NSNumber*) alterarUsingPUT20WithId: (NSNumber*) _id
    persist: (PierTipoOportunidadePersistValue_*) persist
    completionHandler: (void (^)(PierTipoOportunidadeResponse* output, NSError* error)) handler;


///
///
/// {{{tipo_oportunidade_resource_consultar_status}}}
/// {{{tipo_oportunidade_resource_consultar_status_notes}}}
///
/// @param _id {{{tipo_oportunidade_resource_consultar_status_param_id}}}
/// @param idStatus {{{tipo_oportunidade_resource_consultar_status_param_id_status}}}
/// 
///
/// @return PierStatusOportunidadeResponse*
-(NSNumber*) consultarStatusUsingGETWithId: (NSNumber*) _id
    idStatus: (NSNumber*) idStatus
    completionHandler: (void (^)(PierStatusOportunidadeResponse* output, NSError* error)) handler;


///
///
/// {{{oportunidade_resource_consultar}}}
/// {{{oportunidade_resource_consultar_notes}}}
///
/// @param _id {{{oportunidade_resource_consultar_param_id}}}
/// 
///
/// @return PierOportunidadeResponse*
-(NSNumber*) consultarUsingGET25WithId: (NSNumber*) _id
    completionHandler: (void (^)(PierOportunidadeResponse* output, NSError* error)) handler;


///
///
/// {{{tipo_oportunidade_resource_consultar}}}
/// {{{tipo_oportunidade_resource_consultar_notes}}}
///
/// @param _id {{{tipo_oportunidade_resource_consultar_param_id}}}
/// 
///
/// @return PierTipoOportunidadeResponse*
-(NSNumber*) consultarUsingGET44WithId: (NSNumber*) _id
    completionHandler: (void (^)(PierTipoOportunidadeResponse* output, NSError* error)) handler;


///
///
/// {{{tipo_oportunidade_resource_listar_auditorias_status}}}
/// {{{tipo_oportunidade_resource_listar_auditorias_status_notes}}}
///
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param revType {{{status_oportunidade_a_u_d_request_rev_type_value}}}
/// @param revDate {{{status_oportunidade_a_u_d_request_rev_date_value}}}
/// @param _id {{{status_oportunidade_a_u_d_request_id_value}}}
/// @param idTipoOportunidade {{{status_oportunidade_a_u_d_request_id_tipo_oportunidade_value}}}
/// @param nome {{{status_oportunidade_a_u_d_request_nome_value}}}
/// @param descricao {{{status_oportunidade_a_u_d_request_descricao_value}}}
/// @param flagAtivo {{{status_oportunidade_a_u_d_request_flag_ativo_value}}}
/// @param revUser {{{status_oportunidade_a_u_d_request_rev_user_value}}}
/// 
///
/// @return PierPageStatusOportunidadeAUDResponse*
-(NSNumber*) listarAuditoriasStatusUsingGETWithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    revType: (NSNumber*) revType
    revDate: (NSString*) revDate
    _id: (NSNumber*) _id
    idTipoOportunidade: (NSNumber*) idTipoOportunidade
    nome: (NSString*) nome
    descricao: (NSString*) descricao
    flagAtivo: (NSNumber*) flagAtivo
    revUser: (NSString*) revUser
    completionHandler: (void (^)(PierPageStatusOportunidadeAUDResponse* output, NSError* error)) handler;


///
///
/// {{{oportunidade_resource_listar_auditorias}}}
/// {{{oportunidade_resource_listar_auditorias_notes}}}
///
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param idStatusOportunidade {{{oportunidade_a_u_d_request_id_status_oportunidade_value}}}
/// @param dataCadastro {{{oportunidade_a_u_d_request_data_cadastro_value}}}
/// @param dataAtualizacao {{{oportunidade_a_u_d_request_data_atualizacao_value}}}
/// @param numeroReceitaFederal {{{oportunidade_a_u_d_request_numero_receita_federal_value}}}
/// @param dataInicioVigencia {{{oportunidade_a_u_d_request_data_inicio_vigencia_value}}}
/// @param datatFimVigencia {{{oportunidade_a_u_d_request_datat_fim_vigencia_value}}}
/// @param flagAtivo {{{oportunidade_a_u_d_request_flag_ativo_value}}}
/// @param revDate {{{oportunidade_a_u_d_request_rev_date_value}}}
/// @param revType {{{oportunidade_a_u_d_request_rev_type_value}}}
/// @param revUser {{{oportunidade_a_u_d_request_rev_user_value}}}
/// 
///
/// @return PierPageOportunidadeAUDResponse*
-(NSNumber*) listarAuditoriasUsingGETWithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    idStatusOportunidade: (NSNumber*) idStatusOportunidade
    dataCadastro: (NSString*) dataCadastro
    dataAtualizacao: (NSString*) dataAtualizacao
    numeroReceitaFederal: (NSString*) numeroReceitaFederal
    dataInicioVigencia: (NSString*) dataInicioVigencia
    datatFimVigencia: (NSString*) datatFimVigencia
    flagAtivo: (NSNumber*) flagAtivo
    revDate: (NSString*) revDate
    revType: (NSString*) revType
    revUser: (NSString*) revUser
    completionHandler: (void (^)(PierPageOportunidadeAUDResponse* output, NSError* error)) handler;


///
///
/// {{{tipo_oportunidade_resource_listar_auditorias}}}
/// {{{tipo_oportunidade_resource_listar_auditorias_notes}}}
///
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param revType {{{tipo_oportunidade_a_u_d_request_rev_type_value}}}
/// @param revDate {{{tipo_oportunidade_a_u_d_request_rev_date_value}}}
/// @param _id {{{tipo_oportunidade_a_u_d_request_id_value}}}
/// @param descricao {{{tipo_oportunidade_a_u_d_request_descricao_value}}}
/// @param flagAtivo {{{tipo_oportunidade_a_u_d_request_flag_ativo_value}}}
/// @param revUser {{{tipo_oportunidade_a_u_d_request_rev_user_value}}}
/// 
///
/// @return PierPageTipoOportunidadeAUDResponse*
-(NSNumber*) listarAuditoriasUsingGET1WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    revType: (NSNumber*) revType
    revDate: (NSString*) revDate
    _id: (NSNumber*) _id
    descricao: (NSString*) descricao
    flagAtivo: (NSNumber*) flagAtivo
    revUser: (NSString*) revUser
    completionHandler: (void (^)(PierPageTipoOportunidadeAUDResponse* output, NSError* error)) handler;


///
///
/// {{{tipo_oportunidade_resource_listar_status}}}
/// {{{tipo_oportunidade_resource_listar_status_notes}}}
///
/// @param _id {{{tipo_oportunidade_resource_listar_status_param_id}}}
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param nome {{{status_oportunidade_request_nome_value}}}
/// @param descricao {{{status_oportunidade_request_descricao_value}}}
/// @param flagAtivo {{{status_oportunidade_request_flag_ativo_value}}}
/// 
///
/// @return PierPageStatusOportunidadeResponse*
-(NSNumber*) listarStatusUsingGETWithId: (NSNumber*) _id
    sort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    nome: (NSString*) nome
    descricao: (NSString*) descricao
    flagAtivo: (NSNumber*) flagAtivo
    completionHandler: (void (^)(PierPageStatusOportunidadeResponse* output, NSError* error)) handler;


///
///
/// {{{oportunidade_resource_listar}}}
/// {{{oportunidade_resource_listar_notes}}}
///
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param idStatusOportunidade {{{oportunidade_request_id_status_oportunidade_value}}}
/// @param dataCadastro {{{oportunidade_request_data_cadastro_value}}}
/// @param dataAtualizacao {{{oportunidade_request_data_atualizacao_value}}}
/// @param numeroReceitaFederal {{{oportunidade_request_numero_receita_federal_value}}}
/// @param dataInicioVigencia {{{oportunidade_request_data_inicio_vigencia_value}}}
/// @param dataFimVigencia {{{oportunidade_request_data_fim_vigencia_value}}}
/// @param flagAtivo {{{oportunidade_request_flag_ativo_value}}}
/// 
///
/// @return PierPageOportunidadeResponse*
-(NSNumber*) listarUsingGET35WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    idStatusOportunidade: (NSNumber*) idStatusOportunidade
    dataCadastro: (NSString*) dataCadastro
    dataAtualizacao: (NSString*) dataAtualizacao
    numeroReceitaFederal: (NSString*) numeroReceitaFederal
    dataInicioVigencia: (NSString*) dataInicioVigencia
    dataFimVigencia: (NSString*) dataFimVigencia
    flagAtivo: (NSNumber*) flagAtivo
    completionHandler: (void (^)(PierPageOportunidadeResponse* output, NSError* error)) handler;


///
///
/// {{{tipo_oportunidade_resource_listar}}}
/// {{{tipo_oportunidade_resource_listar_notes}}}
///
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param descricao {{{tipo_oportunidade_request_descricao_value}}}
/// @param flagAtivo {{{tipo_oportunidade_request_flag_ativo_value}}}
/// 
///
/// @return PierPageTipoOportunidadeResponse*
-(NSNumber*) listarUsingGET55WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    descricao: (NSString*) descricao
    flagAtivo: (NSNumber*) flagAtivo
    completionHandler: (void (^)(PierPageTipoOportunidadeResponse* output, NSError* error)) handler;


///
///
/// {{{tipo_oportunidade_resource_salvar_status}}}
/// {{{tipo_oportunidade_resource_salvar_status_notes}}}
///
/// @param _id {{{tipo_oportunidade_resource_salvar_status_param_id}}}
/// @param persist persist
/// 
///
/// @return PierStatusOportunidadeResponse*
-(NSNumber*) salvarStatusUsingPOSTWithId: (NSNumber*) _id
    persist: (PierStatusOportunidadePersistValue_*) persist
    completionHandler: (void (^)(PierStatusOportunidadeResponse* output, NSError* error)) handler;


///
///
/// {{{oportunidade_resource_salvar}}}
/// {{{oportunidade_resource_salvar_notes}}}
///
/// @param persist persist
/// 
///
/// @return PierOportunidadeResponse*
-(NSNumber*) salvarUsingPOST21WithPersist: (PierOportunidadePersistValue_*) persist
    completionHandler: (void (^)(PierOportunidadeResponse* output, NSError* error)) handler;


///
///
/// {{{tipo_oportunidade_resource_salvar}}}
/// {{{tipo_oportunidade_resource_salvar_notes}}}
///
/// @param persist persist
/// 
///
/// @return PierTipoOportunidadeResponse*
-(NSNumber*) salvarUsingPOST30WithPersist: (PierTipoOportunidadePersistValue_*) persist
    completionHandler: (void (^)(PierTipoOportunidadeResponse* output, NSError* error)) handler;



@end
