#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierEstGioCartO.h"


@protocol PierListaDeStatusCartEs
@end

@interface PierListaDeStatusCartEs : PierObject

/* Lista de status cart\u00C3\u00B5es [optional]
 */
@property(nonatomic) NSArray<PierEstGioCartO>* statusCartoes;

@end
