#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierArquivoDetalhesPersist.h"


@protocol PierArquivoPersist
@end

@interface PierArquivoPersist : PierObject

/* Tipo do arquivo [optional]
 */
@property(nonatomic) NSNumber* idTipoArquivo;
/* Conte\u00FAdo do arquivo convertido em Base 64 
 */
@property(nonatomic) NSString* arquivo;
/* Nome do arquivo. [optional]
 */
@property(nonatomic) NSString* nome;
/* Formato/extens\u00E3o do arquivo. [optional]
 */
@property(nonatomic) NSString* extensao;
/* Tipo de comunica\u00E7\u00E3o. [optional]
 */
@property(nonatomic) NSString* tipoComunicacao;
/* Detalhes contendo informa\u00E7\u00F5es adicionais, relacionadas ao arquivo 
 */
@property(nonatomic) NSArray<PierArquivoDetalhesPersist>* detalhes;

@end
