#import <Foundation/Foundation.h>
#import "PierPageTaxasRefinanciamentoResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierGlobaltaxasrefinanciamentoApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierGlobaltaxasrefinanciamentoApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierGlobaltaxasrefinanciamentoApi*) sharedAPI;
///
///
/// {{{taxas_refinanciamento_listar}}}
/// {{{taxas_refinanciamento_listar_notes}}}
///
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param _id {{{taxas_refinanciamento_request_id_value}}}
/// @param idProduto {{{taxas_refinanciamento_request_id_produto_value}}}
/// @param dataEntrada {{{taxas_refinanciamento_request_data_entrada_value}}}
/// @param vencimento {{{taxas_refinanciamento_request_vencimento_value}}}
/// 
///
/// @return PierPageTaxasRefinanciamentoResponse*
-(NSNumber*) listarUsingGET51WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    _id: (NSNumber*) _id
    idProduto: (NSNumber*) idProduto
    dataEntrada: (NSString*) dataEntrada
    vencimento: (NSString*) vencimento
    completionHandler: (void (^)(PierPageTaxasRefinanciamentoResponse* output, NSError* error)) handler;



@end
