#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTelefonePessoaAprovadaResponse
@end

@interface PierTelefonePessoaAprovadaResponse : PierObject

/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Endere\u00C3\u00A7o (id) [optional]
 */
@property(nonatomic) NSNumber* _id;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Tipo do Telefone (id). [optional]
 */
@property(nonatomic) NSNumber* idTipoTelefone;
/* C\u00C3\u00B3digo DDD do telefone (id). [optional]
 */
@property(nonatomic) NSString* ddd;
/* N\u00C3\u00BAmero do telefone. [optional]
 */
@property(nonatomic) NSString* telefone;
/* N\u00C3\u00BAmero do ramal. [optional]
 */
@property(nonatomic) NSString* ramal;

@end
