#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierTelefoneResponse.h"


@protocol PierAdicionalResponse
@end

@interface PierAdicionalResponse : PierObject

/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da Conta para cadastro do Adicional [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da Pessoa Adicional [optional]
 */
@property(nonatomic) NSNumber* idPessoa;
/* Nome completo do Adicional [optional]
 */
@property(nonatomic) NSString* nome;
/* Nome do Adicional que ser\u00C3\u00A1 gravado no Cart\u00C3\u00A3o [optional]
 */
@property(nonatomic) NSString* nomeImpresso;
/* N\u00C3\u00BAmero do CPF ou CNPJ do Adicional [optional]
 */
@property(nonatomic) NSString* numeroReceitaFederal;
/* Data de Nascimento do Adicional [optional]
 */
@property(nonatomic) NSString* dataNascimento;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do sexo da Pessoa, quando PF, sendo: (\"M\": Masculino), (\"F\": Feminino), (\"O\": Outro), (\"N\": N\u00C3\u00A3o Especificado). [optional]
 */
@property(nonatomic) NSString* sexo;
/* N\u00C3\u00BAmero do Documento de Identidade do Adicional [optional]
 */
@property(nonatomic) NSString* numeroIdentidade;
/* Nome do Org\u00C3\u00A3o Emissor do Documento de Identidade do Adicional [optional]
 */
@property(nonatomic) NSString* orgaoExpedidorIdentidade;
/* Sigla da Unidade Federativa onde o Documento de Identidade do Adicional foi emitido [optional]
 */
@property(nonatomic) NSString* unidadeFederativaIdentidade;
/* Data de emiss\u00C3\u00A3o do Documento de Identidade do Adicional [optional]
 */
@property(nonatomic) NSString* dataEmissaoIdentidade;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do Estado Civil do Adicional [optional]
 */
@property(nonatomic) NSNumber* idEstadoCivil;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da Profissao do Adicional [optional]
 */
@property(nonatomic) NSNumber* idProfissao;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da Nacionalidade do Adicional [optional]
 */
@property(nonatomic) NSNumber* idNacionalidade;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do Parentesco do Adicional com o Titular [optional]
 */
@property(nonatomic) NSNumber* idParentesco;
/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do Parentesco do Adicional com o Titular [optional]
 */
@property(nonatomic) NSString* email;
/* Indica se o adicional est\u00C3\u00A1 ativo = 1 ou inativo = 0 [optional]
 */
@property(nonatomic) NSNumber* flagAtivo;
/* Lista dos telefones do adicional [optional]
 */
@property(nonatomic) NSArray<PierTelefoneResponse>* telefones;

@end
