#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierFaturaConsignadaDetalheResponse
@end

@interface PierFaturaConsignadaDetalheResponse : PierObject

/* C\u00C3\u00B3digo identificador da fatura. [optional]
 */
@property(nonatomic) NSNumber* _id;
/* C\u00C3\u00B3digo identificador da conta (id). [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* Apresenta o valor do limite de cr\u00C3\u00A9dito que o portador do cart\u00C3\u00A3o possui. 
 */
@property(nonatomic) NSNumber* limiteGlobal;
/* C\u00C3\u00B3digo identificador da conta a qual a fatura se refere. [optional]
 */
@property(nonatomic) NSNumber* flagEmiteFatura;
/* Quando utilizado pelo emissor, este campo apresenta o valor do limite de cr\u00C3\u00A9dito que o portador possui para uso exclusivo em Compras Nacionais. 
 */
@property(nonatomic) NSNumber* limiteCompra;
/* Data de vencimento da fatura. [optional]
 */
@property(nonatomic) NSString* dataVencimentoFatura;
/* Quando utilizado pelo emissor, este campo apresenta o valor do limite de cr\u00C3\u00A9dito que o portador possui para realizar transa\u00C3\u00A7\u00C3\u00B5es de compras parceladas. 
 */
@property(nonatomic) NSNumber* limiteParcelado;
/* Quando utilizado pelo emissor, este campo apresenta o valor do limite de cr\u00C3\u00A9dito que portador pode acumular a partir da soma das parcelas das compras que forem realizadas nesta modalidade. 
 */
@property(nonatomic) NSNumber* limiteParcelas;
/* Valor para pagamento total da fatura. [optional]
 */
@property(nonatomic) NSNumber* valorTotalFatura;
/* Valor total da fatura anterior. [optional]
 */
@property(nonatomic) NSNumber* valorFaturaAnterior;
/* Valor m\u00C3\u00ADnimo para pagamento da fatura. [optional]
 */
@property(nonatomic) NSNumber* valorPagamentoMinimo;
/* Valor da fatura pago atrav\u00C3\u00A9s de desconto em folha. [optional]
 */
@property(nonatomic) NSNumber* valorPagamentoConsignado;
/* Quando utilizado pelo emissor, este campo apresenta o valor do limite de cr\u00C3\u00A9dito que o portador pode utilizar para realizar transa\u00C3\u00A7\u00C3\u00B5es de Saque Nacional. 
 */
@property(nonatomic) NSNumber* limiteSaqueGlobal;
/* Valor complementar para considerar o pagamento m\u00C3\u00ADnimo da fatura. [optional]
 */
@property(nonatomic) NSNumber* valorPagamentoComplementar;
/* Quando utilizado pelo emissor, este campo apresenta o valor do limite de cr\u00C3\u00A9dito que o portador pode utilizar para realizar transa\u00C3\u00A7\u00C3\u00B5es de Saque Nacional dentro de cada ciclo de faturamento. 
 */
@property(nonatomic) NSNumber* limiteSaquePeriodo;
/* Valor total das compras nacionais lan\u00C3\u00A7adas na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalComprasNacionais;
/* Quando utilizado pelo emissor, este campo apresenta o valor da margem de cr\u00C3\u00A9dito que ele poder\u00C3\u00A1 utilizar para ser cobrado de forma consignada (desconto em folha) em seu sal\u00C3\u00A1rio/vencimentos. 
 */
@property(nonatomic) NSNumber* limiteConsignado;
/* Valor total das compras internacionais lan\u00C3\u00A7adas na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalComprasInternacionas;
/* Quando utilizado pelo emissor, este campo apresenta o valor do limite de cr\u00C3\u00A9dito que o portador possui para uso exclusivo em Compras Internacionais. 
 */
@property(nonatomic) NSNumber* limiteInternacionalCompra;
/* Valor total dos saques nacionais lan\u00C3\u00A7ados na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalSaquesNacionais;
/* Quando utilizado pelo emissor, este campo apresenta o valor do limite de cr\u00C3\u00A9dito que o portador possui para realizar transa\u00C3\u00A7\u00C3\u00B5es Internacionais de Compras Parceladas. 
 */
@property(nonatomic) NSNumber* limiteInternacionalParcelado;
/* Valor total dos saques internacionais lan\u00C3\u00A7ados na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalSaquesInternacionais;
/* Quando utilizado pelo emissor, este campo apresenta o valor do limite de cr\u00C3\u00A9dito que portador pode acumular a partir da soma das parcelas das compras internacionais que forem realizadas nesta modalidade. 
 */
@property(nonatomic) NSNumber* limiteInternacionalParcelas;
/* Valor total dos d\u00C3\u00A9bitos nacionais lan\u00C3\u00A7ados na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalDebitosNacionais;
/* Quando utilizado pelo emissor, este campo apresenta o valor do limite de cr\u00C3\u00A9dito que o portador pode utilizar para realizar transa\u00C3\u00A7\u00C3\u00B5es de Saque Internacional. 
 */
@property(nonatomic) NSNumber* limiteInternacionalSaqueGlobal;
/* Valor total dos d\u00C3\u00A9bitos recorrentes lan\u00C3\u00A7ados na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalDebitosRecorrentes;
/* Quando utilizado pelo emissor, este campo apresenta o valor do limite de cr\u00C3\u00A9dito que o portador pode utilizar para realizar transa\u00C3\u00A7\u00C3\u00B5es de Saque Internacional dentro de cada ciclo de faturamento. 
 */
@property(nonatomic) NSNumber* limiteInternacionalSaquePeriodo;
/* Valor total dos d\u00C3\u00A9bitos internacionais lan\u00C3\u00A7ados na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalDebitosInternacionais;
/* Apresenta o valor de cr\u00C3\u00A9dito que o portador possui dispon\u00C3\u00ADvel para realizar transa\u00C3\u00A7\u00C3\u00B5es. 
 */
@property(nonatomic) NSNumber* saldoDisponivelGlobal;
/* Valor total dos d\u00C3\u00A9bitos diversos nacionais lan\u00C3\u00A7ados na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalDebitosDiversosNacionais;
/* Quando utilizado pelo emissor a modalidade limiteCompra, este campo apresentar\u00C3\u00A1 o valor de cr\u00C3\u00A9dito que o portador possui dispon\u00C3\u00ADvel para realizar transa\u00C3\u00A7\u00C3\u00B5es de compra Nacional. 
 */
@property(nonatomic) NSNumber* saldoDisponivelCompra;
/* Valor total dos d\u00C3\u00A9bitos diversos opcionais lan\u00C3\u00A7ados na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalDebitosOpcionais;
/* Quando utilizado pelo emissor a modalidade limiteParcelado, este campo apresentar\u00C3\u00A1 o valor de cr\u00C3\u00A9dito que o portador possui dispon\u00C3\u00ADvel para realizar transa\u00C3\u00A7\u00C3\u00B5es de compra Nacional. 
 */
@property(nonatomic) NSNumber* saldoDisponivelParcelado;
/* Valor total dos pagamentos lan\u00C3\u00A7ados na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalPagamentos;
/* Quando utilizado pelo emissor a modalidade limiteParcelas, este campo apresentar\u00C3\u00A1 o valor de cr\u00C3\u00A9dito que o portador possui dispon\u00C3\u00ADvel para utilizar como valor de parcelas Nacionais em um determinado ciclo de faturamento. 
 */
@property(nonatomic) NSNumber* saldoDisponivelParcelas;
/* Valor total dos cr\u00C3\u00A9ditos nacionais lan\u00C3\u00A7ados na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalCreditosNacionais;
/* Valor total dos ajustes lan\u00C3\u00A7ados na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalAjustes;
/* Valor total das tarifas lan\u00C3\u00A7adas na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalTarifas;
/* Valor total da multa lan\u00C3\u00A7ada na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalMulta;
/* Quando utilizado pelo emissor a modalidade limiteSaque, este campo apresentar\u00C3\u00A1 o valor de cr\u00C3\u00A9dito que o portador possui dispon\u00C3\u00ADvel para realizar transa\u00C3\u00A7\u00C3\u00B5es de Saque Nacional. 
 */
@property(nonatomic) NSNumber* saldoDisponivelSaque;
/* Valor total dos juros de mora lan\u00C3\u00A7ados na fatura. [optional]
 */
@property(nonatomic) NSNumber* totalJuros;
/* Quando utilizado um programa de fidelidade pelo emissor, este campo apresentar\u00C3\u00A1 o saldo atual de pontos que o portador possui. 
 */
@property(nonatomic) NSNumber* saldoPontosFidelidade;
/* Valor percentual da taxa de juros rotativos. [optional]
 */
@property(nonatomic) NSNumber* taxaRotativo;
/* Quando utilizado pelo emissor a modalidade limiteCompraInternacional, este campo apresentar\u00C3\u00A1 o valor de cr\u00C3\u00A9dito que o portador possui dispon\u00C3\u00ADvel para realizar transa\u00C3\u00A7\u00C3\u00B5es de Compra Internacional. 
 */
@property(nonatomic) NSNumber* saldoDisponivelCompraInternacional;
/* Valor percentual da taxa de saque. [optional]
 */
@property(nonatomic) NSNumber* taxaSaque;
/* Quando utilizado pelo emissor a modalidade limiteSaqueInternacional, este campo apresentar\u00C3\u00A1 o valor de cr\u00C3\u00A9dito que o portador possui dispon\u00C3\u00ADvel para realizar transa\u00C3\u00A7\u00C3\u00B5es de Saque Internacional. 
 */
@property(nonatomic) NSNumber* saldoDisponivelSaqueInternacional;
/* Valor m\u00C3\u00A1ximo percentual da taxa de encargos para o pr\u00C3\u00B3ximo per\u00C3\u00ADodo. [optional]
 */
@property(nonatomic) NSNumber* taxaMaximaProximoPeriodo;
/* Apresenta a soma de todos os seguros cobrados na fatura do cliente. 
 */
@property(nonatomic) NSNumber* totalServicos;

@end
