#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTransferenciaCreditoContaBancariaListaResponse
@end

@interface PierTransferenciaCreditoContaBancariaListaResponse : PierObject

/* C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da transferencia. [optional]
 */
@property(nonatomic) NSNumber* idTransferencia;
/* Valor da transfer\u00C3\u00AAncia. [optional]
 */
@property(nonatomic) NSNumber* valorCompra;
/* Valor da transfer\u00C3\u00AAncia acrescido do valor da tarifa de saque se houver tarifa de saque. [optional]
 */
@property(nonatomic) NSNumber* valorContrato;
/* Data da transfer\u00C3\u00AAncia. [optional]
 */
@property(nonatomic) NSString* dataCompra;
/* Status Processamento. [optional]
 */
@property(nonatomic) NSString* statusProcessamento;

@end
