#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierCompraResponse
@end

@interface PierCompraResponse : PierObject


@property(nonatomic) NSNumber* mcc;

@property(nonatomic) NSString* uf;
/* C\u00F3digo de identifica\u00E7\u00E3o da compra. [optional]
 */
@property(nonatomic) NSNumber* idCompra;
/* Descri\u00E7\u00E3o do status da autoriza\u00E7\u00E3o da compra. [optional]
 */
@property(nonatomic) NSString* status;
/* Data da compra. [optional]
 */
@property(nonatomic) NSString* dataCompra;
/* Valor total da compra. [optional]
 */
@property(nonatomic) NSNumber* valorTotalCompra;
/* Valor da parcela da compra. [optional]
 */
@property(nonatomic) NSNumber* valorParcela;
/* Valor da primeira parcela da compra. [optional]
 */
@property(nonatomic) NSNumber* primeiraParcela;
/* N\u00FAmero de parcelas da compra. [optional]
 */
@property(nonatomic) NSNumber* numeroParcelas;
/* N\u00FAmero de parcelas antecip\u00E1veis da compra. [optional]
 */
@property(nonatomic) NSNumber* numeroParcelasAntecipaveis;
/* Nome do estabelecimento da compra. [optional]
 */
@property(nonatomic) NSString* nomeEstabelecimento;
/* Tipo de transa\u00E7\u00E3o da compra. [optional]
 */
@property(nonatomic) NSString* tipoOrigemTransacao;
/* Cidade onde a compra foi realizada. [optional]
 */
@property(nonatomic) NSString* cidade;
/* Pa\u00EDs onde a compra foi realizada. [optional]
 */
@property(nonatomic) NSString* pais;
/* Coordenada latitudinal da localiza\u00E7\u00E3o da compra. [optional]
 */
@property(nonatomic) NSString* latitude;
/* Coordenada longitudinal da localiza\u00E7\u00E3o da compra. [optional]
 */
@property(nonatomic) NSString* longitude;
/* C\u00F3digo de Identifica\u00E7\u00E3o do Grupo MCC da compra. [optional]
 */
@property(nonatomic) NSNumber* idGrupoMCC;
/* Descri\u00E7\u00E3o do Grupo MCC da compra. [optional]
 */
@property(nonatomic) NSString* descricaoGrupoMCC;
/* C\u00F3digo de Identifica\u00E7\u00E3o da conta da compra. [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* C\u00F3digo de Identifica\u00E7\u00E3o do produto da compra. [optional]
 */
@property(nonatomic) NSNumber* idProduto;
/* Descri\u00E7\u00E3o do produto da compra. [optional]
 */
@property(nonatomic) NSString* descricaoProduto;
/* N\u00FAmero do cart\u00E3o da compra. [optional]
 */
@property(nonatomic) NSString* cartao;
/* Nome do portador do cart\u00E3o da compra. [optional]
 */
@property(nonatomic) NSString* nomePortadorCartao;

@end
