#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierStatusArquivoResponse
@end

@interface PierStatusArquivoResponse : PierObject

/* {{{status_arquivo_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{status_arquivo_response_nome_value}}} [optional]
 */
@property(nonatomic) NSString* nome;
/* {{{status_arquivo_response_descricao_value}}} [optional]
 */
@property(nonatomic) NSString* descricao;

@end
