#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierDadosCartO
@end

@interface PierDadosCartO : PierObject


@property(nonatomic) NSNumber* flagVirtual;
/* N\u00C3\u00BAmero do cart\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSString* numeroCartao;
/* Data de validade. [optional]
 */
@property(nonatomic) NSString* dataValidade;
/* CVV2 do cart\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSString* cvv2;
/* Nome do portador. [optional]
 */
@property(nonatomic) NSString* nomePlastico;
/* Identificador da conta do portador. [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* Identificador da cart\u00C3\u00A3o do portador. [optional]
 */
@property(nonatomic) NSNumber* idCartao;
/* Apresenta o n\u00C3\u00BAmero da Ag\u00C3\u00AAncia a ser impresso no Cart\u00C3\u00A3o, quando aplic\u00C3\u00A1vel. [optional]
 */
@property(nonatomic) NSNumber* numeroAgencia;
/* Apresenta o n\u00C3\u00BAmero da Conta Corrente a ser impresso no Cart\u00C3\u00A3o, quando aplic\u00C3\u00A1vel. [optional]
 */
@property(nonatomic) NSString* numeroContaCorente;
/* Status da conta do portador. [optional]
 */
@property(nonatomic) NSNumber* idStatusConta;
/* Descri\u00C3\u00A7\u00C3\u00A3o do status da conta do portador. [optional]
 */
@property(nonatomic) NSString* statusConta;
/* Status do cart\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSNumber* idStatusCartao;
/* Descri\u00C3\u00A7\u00C3\u00A3o do status do cart\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSString* statusCartao;

@end
