#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierCartaoPayDetalheResponse
@end

@interface PierCartaoPayDetalheResponse : PierObject

/* Id do cart\u00E3o [optional]
 */
@property(nonatomic) NSNumber* _id;
/* N\u00FAmero do cart\u00E3o real criptografado [optional]
 */
@property(nonatomic) NSString* numeroCartao;
/* Data de validade do cart\u00E3o [optional]
 */
@property(nonatomic) NSString* dataValidadeCartao;
/* Nome impresso no cart\u00E3o criptografado [optional]
 */
@property(nonatomic) NSString* nomeImpresso;
/* Identificador do emissor do cart\u00E3o [optional]
 */
@property(nonatomic) NSNumber* idEntidade;
/* Nome do emissor do cart\u00E3o [optional]
 */
@property(nonatomic) NSString* nomeEntidade;
/* Status do cart\u00E3o [optional]
 */
@property(nonatomic) NSString* status;
/* CVV do cart\u00E3o criptografado [optional]
 */
@property(nonatomic) NSString* cvv;
/* Data de validade da chave do criptograma [optional]
 */
@property(nonatomic) NSString* dataValidadeChaveCriptograma;

@end
