#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierCampoCodificadoDescricaoResponse
@end

@interface PierCampoCodificadoDescricaoResponse : PierObject

/* C\u00F3digo de Identifica\u00E7\u00E3o da descri\u00E7\u00E3o. [optional]
 */
@property(nonatomic) NSNumber* codigo;
/* Descri\u00E7\u00E3o do campo codificado. [optional]
 */
@property(nonatomic) NSString* descricao;

@end
