#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierTelefoneResponse.h"


@protocol PierRiscoFraudeDetalhadoResponse
@end

@interface PierRiscoFraudeDetalhadoResponse : PierObject

/* {{{risco_fraude_detalhado_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{risco_fraude_detalhado_response_id_tipo_resolucao_value}}} [optional]
 */
@property(nonatomic) NSNumber* idTipoResolucao;
/* {{{risco_fraude_detalhado_response_descricao_tipo_resolucao_value}}} [optional]
 */
@property(nonatomic) NSString* descricaoTipoResolucao;
/* {{{risco_fraude_detalhado_response_flag_alto_risco_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagAltoRisco;
/* {{{risco_fraude_detalhado_response_id_conta_value}}} [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* {{{risco_fraude_detalhado_response_id_cartao_value}}} [optional]
 */
@property(nonatomic) NSNumber* idCartao;
/* {{{risco_fraude_detalhado_response_id_produto_value}}} [optional]
 */
@property(nonatomic) NSNumber* idProduto;
/* {{{risco_fraude_detalhado_response_id_transacao_value}}} [optional]
 */
@property(nonatomic) NSNumber* idTransacao;
/* {{{risco_fraude_detalhado_response_data_transacao_value}}} [optional]
 */
@property(nonatomic) NSString* dataTransacao;
/* {{{risco_fraude_detalhado_response_valor_transacao_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorTransacao;
/* {{{risco_fraude_detalhado_response_codigo_moeda_origem_value}}} [optional]
 */
@property(nonatomic) NSString* codigoMoedaOrigem;
/* {{{risco_fraude_detalhado_response_valor_origem_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorOrigem;
/* {{{risco_fraude_detalhado_response_codigo_moeda_destino_value}}} [optional]
 */
@property(nonatomic) NSString* codigoMoedaDestino;
/* {{{risco_fraude_detalhado_response_valor_destino_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorDestino;
/* {{{risco_fraude_detalhado_response_nome_estabelecimento_value}}} [optional]
 */
@property(nonatomic) NSString* nomeEstabelecimento;
/* {{{risco_fraude_detalhado_response_id_pais_value}}} [optional]
 */
@property(nonatomic) NSString* idPais;
/* {{{risco_fraude_detalhado_response_codigo_resposta_autorizador_value}}} [optional]
 */
@property(nonatomic) NSString* codigoRespostaAutorizador;
/* {{{risco_fraude_detalhado_response_descricao_resposta_autorizador_value}}} [optional]
 */
@property(nonatomic) NSString* descricaoRespostaAutorizador;
/* {{{risco_fraude_detalhado_response_codigo_resposta_fraude_value}}} [optional]
 */
@property(nonatomic) NSString* codigoRespostaFraude;
/* {{{risco_fraude_detalhado_response_descricao_resposta_fraude_value}}} [optional]
 */
@property(nonatomic) NSString* descricaoRespostaFraude;
/* {{{risco_fraude_detalhado_response_origem_transacao_value}}} [optional]
 */
@property(nonatomic) NSString* origemTransacao;
/* {{{risco_fraude_detalhado_response_codigo_modo_entrada_terminal_value}}} [optional]
 */
@property(nonatomic) NSString* codigoModoEntradaTerminal;
/* {{{risco_fraude_detalhado_response_descricao_modo_entrada_terminal_value}}} [optional]
 */
@property(nonatomic) NSString* descricaoModoEntradaTerminal;
/* {{{risco_fraude_detalhado_response_cpf_value}}} [optional]
 */
@property(nonatomic) NSString* cpf;
/* {{{risco_fraude_detalhado_response_cnpj_value}}} [optional]
 */
@property(nonatomic) NSString* cnpj;
/* {{{risco_fraude_detalhado_response_email_value}}} [optional]
 */
@property(nonatomic) NSString* email;
/* {{{risco_fraude_detalhado_response_telefones_value}}} [optional]
 */
@property(nonatomic) NSArray<PierTelefoneResponse>* telefones;

@end
