#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTipoOportunidadeAUDResponse
@end

@interface PierTipoOportunidadeAUDResponse : PierObject

/* {{{tipo_oportunidade_a_u_d_response_rev_value}}} [optional]
 */
@property(nonatomic) NSNumber* rev;
/* {{{tipo_oportunidade_a_u_d_response_rev_type_value}}} [optional]
 */
@property(nonatomic) NSNumber* revType;
/* {{{tipo_oportunidade_a_u_d_response_rev_date_value}}} [optional]
 */
@property(nonatomic) NSString* revDate;
/* {{{tipo_oportunidade_a_u_d_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{tipo_oportunidade_a_u_d_response_descricao_value}}} [optional]
 */
@property(nonatomic) NSString* descricao;
/* {{{tipo_oportunidade_a_u_d_response_flag_ativo_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagAtivo;

@end
