#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierPlanoParcelamentoEmprestimoResponse
@end

@interface PierPlanoParcelamentoEmprestimoResponse : PierObject

/* N\u00C3\u00BAmeros de parcelas do empr\u00C3\u00A9stimo/financiamento [optional]
 */
@property(nonatomic) NSNumber* numeroParcelas;
/* Valor da parcela [optional]
 */
@property(nonatomic) NSNumber* valorParcelas;
/* Taxa de juros aplicado no empr\u00C3\u00A9stimo/financiamento [optional]
 */
@property(nonatomic) NSNumber* taxaJuros;
/* valor total estimado dos tributos do Imposto sobre Opera\u00C3\u00A7\u00C3\u00B5es Financeiras [optional]
 */
@property(nonatomic) NSNumber* valorTributosIOF;
/* valor percentual do Custo Efetivo Total, ao ano, do empr\u00C3\u00A9stimo / financiamento [optional]
 */
@property(nonatomic) NSNumber* valorPercentualCET;

@end
