#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierArquivoDetalhesPersist.h"


@protocol PierArquivoPersist
@end

@interface PierArquivoPersist : PierObject

/* {{{arquivo_persist_id_tipo_arquivo_value}}} [optional]
 */
@property(nonatomic) NSNumber* idTipoArquivo;
/* {{{arquivo_persist_arquivo_value}}} 
 */
@property(nonatomic) NSString* arquivo;
/* {{{arquivo_persist_nome_value}}} [optional]
 */
@property(nonatomic) NSString* nome;
/* {{{arquivo_persist_extensao_value}}} [optional]
 */
@property(nonatomic) NSString* extensao;
/* {{{arquivo_persist_tipo_comunicacao_value}}} [optional]
 */
@property(nonatomic) NSString* tipoComunicacao;
/* {{{arquivo_persist_detalhes_value}}} 
 */
@property(nonatomic) NSArray<PierArquivoDetalhesPersist>* detalhes;

@end
