#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierOperacaoResponse
@end

@interface PierOperacaoResponse : PierObject

/* {{{operacao_response_id_operacao_value}}} [optional]
 */
@property(nonatomic) NSNumber* idOperacao;
/* {{{operacao_response_codigo_processamento_value}}} [optional]
 */
@property(nonatomic) NSString* codigoProcessamento;
/* {{{operacao_response_codigo_processamento_cancelamento_value}}} [optional]
 */
@property(nonatomic) NSString* codigoProcessamentoCancelamento;
/* {{{operacao_response_nome_operacao_value}}} [optional]
 */
@property(nonatomic) NSString* nomeOperacao;
/* {{{operacao_response_flag_cobra_juros_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagCobraJuros;
/* {{{operacao_response_flag_cobra_tarifa_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagCobraTarifa;
/* {{{operacao_response_carencia_value}}} [optional]
 */
@property(nonatomic) NSNumber* carencia;
/* {{{operacao_response_flag_permitir_parcelamento_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagPermitirParcelamento;

@end
