#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierParcelamentoTransferenciaResponse.h"


@protocol PierPlanoParcelamentoTransferenciaResponse
@end

@interface PierPlanoParcelamentoTransferenciaResponse : PierObject

/* C\u00C3\u00B3digo de processamento da transa\u00C3\u00A7\u00C3\u00A3o. [optional]
 */
@property(nonatomic) NSNumber* codigoEspecial;
/* Data de vencimento da primeira parcela. [optional]
 */
@property(nonatomic) NSString* vencimentoPrimeiraParcela;
/* Flag indicativa para juros. [optional]
 */
@property(nonatomic) NSNumber* flagJuros;
/* N\u00C3\u00BAmero de meses para car\u00C3\u00AAncia. [optional]
 */
@property(nonatomic) NSNumber* numeroMesesCarencia;
/* Lista com os planos de parcelamento. [optional]
 */
@property(nonatomic) NSArray<PierParcelamentoTransferenciaResponse>* parcelas;

@end
