#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierDetalheOportunidadeResponse.h"


@protocol PierOportunidadeResponse
@end

@interface PierOportunidadeResponse : PierObject

/* {{{oportunidade_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{oportunidade_response_id_tipo_oportunidade_value}}} [optional]
 */
@property(nonatomic) NSNumber* idTipoOportunidade;
/* {{{oportunidade_response_id_status_oportunidade_value}}} [optional]
 */
@property(nonatomic) NSNumber* idStatusOportunidade;
/* {{{oportunidade_response_data_cadastro_value}}} [optional]
 */
@property(nonatomic) NSString* dataCadastro;
/* {{{oportunidade_response_data_atualizacao_value}}} [optional]
 */
@property(nonatomic) NSString* dataAtualizacao;
/* {{{oportunidade_response_numero_receita_federal_value}}} [optional]
 */
@property(nonatomic) NSString* numeroReceitaFederal;
/* {{{oportunidade_response_data_inicio_vigencia_value}}} [optional]
 */
@property(nonatomic) NSString* dataInicioVigencia;
/* {{{oportunidade_response_data_fim_vigencia_value}}} [optional]
 */
@property(nonatomic) NSString* dataFimVigencia;
/* {{{oportunidade_response_flag_ativo_value}}} [optional]
 */
@property(nonatomic) NSNumber* flagAtivo;
/* {{{oportunidade_response_detalhes_value}}} [optional]
 */
@property(nonatomic) NSArray<PierDetalheOportunidadeResponse>* detalhes;

@end
