#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierPlanoCampanhaResponse
@end

@interface PierPlanoCampanhaResponse : PierObject

/* {{{plano_campanha_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{plano_campanha_response_parcelas_value}}} [optional]
 */
@property(nonatomic) NSNumber* parcelas;
/* {{{plano_campanha_response_taxa_value}}} [optional]
 */
@property(nonatomic) NSNumber* taxa;
/* {{{plano_campanha_response_usuario_value}}} [optional]
 */
@property(nonatomic) NSString* usuario;

@end
