#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierHistoricoPagamentoResponse
@end

@interface PierHistoricoPagamentoResponse : PierObject

/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o da Conta [optional]
 */
@property(nonatomic) NSNumber* idConta;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Pagamento [optional]
 */
@property(nonatomic) NSNumber* idPagamento;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Estabelecimento onde o Pagamento foi realizado, quando este for o local de pagamento. [optional]
 */
@property(nonatomic) NSNumber* idEstabelecimento;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o da Institui\u00C3\u00A7\u00C3\u00A3o Banc\u00C3\u00A1ria onde o Pagamento foi realizado, quando este for o local de pagamento [optional]
 */
@property(nonatomic) NSNumber* idBanco;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Cart\u00C3\u00A3o [optional]
 */
@property(nonatomic) NSNumber* idCartao;
/* Valor do Pagamento [optional]
 */
@property(nonatomic) NSNumber* valorPagamento;
/* Data e Hora da realiza\u00C3\u00A7\u00C3\u00A3o do Pagamento. Quando feito em Institui\u00C3\u00A7\u00C3\u00A3o Banc\u00C3\u00A1ria, o hor\u00C3\u00A1rio do pagamento \u00C3\u00A9 exibido com valor zero [optional]
 */
@property(nonatomic) NSString* dataHoraPagamento;
/* Data e Hora em que o registro do Pagamento foi cadastrado [optional]
 */
@property(nonatomic) NSString* dataHoraEntradaPagamento;
/* Data e Hora do vencimento da parcela do acordo [optional]
 */
@property(nonatomic) NSString* dataVencimentoParcelaAcordo;
/* C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o do Status do Pagamento [optional]
 */
@property(nonatomic) NSNumber* status;

@end
