#import <Foundation/Foundation.h>
#import "PierAjusteFinanceiroResponse.h"
#import "PierPageAjusteResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierGlobaltagajustefinanceiroApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierGlobaltagajustefinanceiroApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierGlobaltagajustefinanceiroApi*) sharedAPI;
///
///
/// {{{ajuste_financeiro_resource_ajustar_conta}}}
/// {{{ajuste_financeiro_resource_ajustar_conta_notes}}}
///
/// @param idTipoAjuste {{{ajuste_financeiro_persist_id_tipo_ajuste_value}}}
/// @param dataAjuste {{{ajuste_financeiro_persist_data_ajuste_value}}}
/// @param valorAjuste {{{ajuste_financeiro_persist_valor_ajuste_value}}}
/// @param idConta {{{ajuste_financeiro_persist_id_conta_value}}}
/// @param identificadorExterno {{{ajuste_financeiro_persist_identificador_externo_value}}}
/// @param idTransacaoOriginal {{{ajuste_persist_id_transacao_original}}}
/// 
///
/// @return PierAjusteFinanceiroResponse*
-(NSNumber*) ajustarContaUsingPOSTWithIdTipoAjuste: (NSNumber*) idTipoAjuste
    dataAjuste: (NSString*) dataAjuste
    valorAjuste: (NSNumber*) valorAjuste
    idConta: (NSNumber*) idConta
    identificadorExterno: (NSString*) identificadorExterno
    idTransacaoOriginal: (NSNumber*) idTransacaoOriginal
    completionHandler: (void (^)(PierAjusteFinanceiroResponse* output, NSError* error)) handler;


///
///
/// {{{ajuste_financeiro_resource_consultar}}}
/// {{{ajuste_financeiro_resource_consultar_notes}}}
///
/// @param _id {{{ajuste_financeiro_resource_consultar_param_id}}}
/// 
///
/// @return PierAjusteFinanceiroResponse*
-(NSNumber*) consultarUsingGET2WithId: (NSNumber*) _id
    completionHandler: (void (^)(PierAjusteFinanceiroResponse* output, NSError* error)) handler;


///
///
/// {{{ajuste_financeiro_resource_listar}}}
/// {{{ajuste_financeiro_resource_listar_notes}}}
///
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// @param idTipoAjuste {{{ajuste_request_id_tipo_ajuste_value}}}
/// @param dataAjuste {{{ajuste_request_data_ajuste_value}}}
/// @param valorAjuste {{{ajuste_request_valor_ajuste_value}}}
/// @param identificadorExterno {{{ajuste_request_identificador_externo_value}}}
/// @param idConta {{{ajuste_request_id_conta_value}}}
/// 
///
/// @return PierPageAjusteResponse*
-(NSNumber*) listarUsingGET2WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    idTipoAjuste: (NSNumber*) idTipoAjuste
    dataAjuste: (NSString*) dataAjuste
    valorAjuste: (NSNumber*) valorAjuste
    identificadorExterno: (NSString*) identificadorExterno
    idConta: (NSNumber*) idConta
    completionHandler: (void (^)(PierPageAjusteResponse* output, NSError* error)) handler;



@end
