#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierEstagioCartaoResponse
@end

@interface PierEstagioCartaoResponse : PierObject

/* {{{estagio_cartao_response_id_value}}} 
 */
@property(nonatomic) NSNumber* _id;
/* {{{estagio_cartao_response_nome_value}}} 
 */
@property(nonatomic) NSString* nome;

@end
