#import <Foundation/Foundation.h>
#import "PierPageHistoricoEventosResponse.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierGlobaltaglimiteApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierGlobaltaglimiteApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierGlobaltaglimiteApi*) sharedAPI;
///
///
/// {{{conta_resource_listar_historico_alteracoes_limites}}}
/// {{{conta_resource_listar_historico_alteracoes_limites_notes}}}
///
/// @param _id {{{conta_resource_listar_historico_alteracoes_limites_param_id}}}
/// @param sort {{{global_menssagem_sort_sort}}}
/// @param page {{{global_menssagem_sort_page_value}}}
/// @param limit {{{global_menssagem_sort_limit}}}
/// 
///
/// @return PierPageHistoricoEventosResponse*
-(NSNumber*) listarHistoricoAlteracoesLimitesUsingGETWithId: (NSNumber*) _id
    sort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    completionHandler: (void (^)(PierPageHistoricoEventosResponse* output, NSError* error)) handler;



@end
