#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierDocumentoDetalheResponse
@end

@interface PierDocumentoDetalheResponse : PierObject

/* ID de identifica\u00E7\u00E3o do detalhamento do documento. [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Propriedade do detalhamento do documento. [optional]
 */
@property(nonatomic) NSString* propriedade;
/* Conte\u00FAdo do detalhamento do documento. [optional]
 */
@property(nonatomic) NSString* conteudo;

@end
