#import <Foundation/Foundation.h>
#import "PierAplicacaoMobileUpdate.h"
#import "PierAplicacaoMobileResponse.h"
#import "PierPageAplicacaoMobileResponse.h"
#import "PierAplicacaoMobilePersist.h"
#import "PierObject.h"
#import "PierApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface PierAplicacaoMobileApi: NSObject

@property(nonatomic, assign)PierApiClient *apiClient;

-(instancetype) initWithApiClient:(PierApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(PierAplicacaoMobileApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(PierAplicacaoMobileApi*) sharedAPI;
///
///
/// Atualiza Aplicacao Mobile
/// Esse recurso permite atualizar aplicacao mobile.
///
/// @param _id C\u00F3digo de Identifica\u00E7\u00E3o da Aplicacao (id).
/// @param update update
/// 
///
/// @return PierAplicacaoMobileResponse*
-(NSNumber*) atualizarUsingPUTWithId: (NSNumber*) _id
    update: (PierAplicacaoMobileUpdate*) update
    completionHandler: (void (^)(PierAplicacaoMobileResponse* output, NSError* error)) handler;


///
///
/// Lista os aplicacoes mobile cadastradas
/// Este m\u00E9todo permite que sejam listadas as aplicacoes mobile existentes na base do PIER.
///
/// @param sort Tipo de ordena\u00E7\u00E3o dos registros.
/// @param page P\u00E1gina solicitada (Default = 0)
/// @param limit Limite de elementos por solicita\u00E7\u00E3o (Default = 50, Max = 50)
/// @param _id Identificador da Aplicacao Mobile
/// @param idPlataformaMobile Identificador da Plataforma Mobile
/// 
///
/// @return PierPageAplicacaoMobileResponse*
-(NSNumber*) listarUsingGET3WithSort: (NSArray* /* NSString */) sort
    page: (NSNumber*) page
    limit: (NSNumber*) limit
    _id: (NSString*) _id
    idPlataformaMobile: (NSNumber*) idPlataformaMobile
    completionHandler: (void (^)(PierPageAplicacaoMobileResponse* output, NSError* error)) handler;


///
///
/// Cadastra Aplicacao Mobile
/// Esse recurso permite cadastrar aplicacoes mobile.
///
/// @param persist persist
/// 
///
/// @return PierAplicacaoMobileResponse*
-(NSNumber*) salvarUsingPOSTWithPersist: (PierAplicacaoMobilePersist*) persist
    completionHandler: (void (^)(PierAplicacaoMobileResponse* output, NSError* error)) handler;



@end
