#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierAutorizacaoOnUsRequest
@end

@interface PierAutorizacaoOnUsRequest : PierObject

/* {{{transacao_on_us_request_nsu_origem_value}}} 
 */
@property(nonatomic) NSString* nsuOrigem;
/* {{{autorizacao_on_us_request_numero_parcelas_value}}} 
 */
@property(nonatomic) NSNumber* numeroParcelas;
/* {{{transacao_on_us_request_codigo_processamento_value}}} 
 */
@property(nonatomic) NSString* codigoProcessamento;
/* {{{autorizacao_on_us_request_codigo_seguranca_cartao_value}}} [optional]
 */
@property(nonatomic) NSString* codigoSegurancaCartao;
/* {{{transacao_on_us_request_valor_transacao_value}}} 
 */
@property(nonatomic) NSNumber* valorTransacao;
/* {{{transacao_on_us_request_numero_real_cartao_value}}} 
 */
@property(nonatomic) NSString* numeroRealCartao;
/* {{{transacao_on_us_request_data_validade_cartao_value}}} 
 */
@property(nonatomic) NSString* dataValidadeCartao;
/* {{{transacao_on_us_request_numero_estabelecimento_value}}} 
 */
@property(nonatomic) NSNumber* numeroEstabelecimento;
/* {{{transacao_on_us_request_data_hora_terminal_value}}} 
 */
@property(nonatomic) NSString* dataHoraTerminal;
/* {{{transacao_on_us_request_terminal_requisitante_value}}} 
 */
@property(nonatomic) NSString* terminalRequisitante;

@end
