#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierCodigoChargebackResponse
@end

@interface PierCodigoChargebackResponse : PierObject

/* {{{codigo_chargeback_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{codigo_chargeback_response_descricao_value}}} [optional]
 */
@property(nonatomic) NSString* descricao;

@end
