#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierConfiguracaoRotativoPersist
@end

@interface PierConfiguracaoRotativoPersist : PierObject

/* {{{configuracao_rotativo_persist_id_produto_value}}} [optional]
 */
@property(nonatomic) NSNumber* idProduto;
/* {{{configuracao_rotativo_persist_compoe_oferta_valor_rotativo_value}}} [optional]
 */
@property(nonatomic) NSNumber* compoeOfertaValorRotativo;
/* {{{configuracao_rotativo_persist_compoe_oferta_valor_nao_financiavel_value}}} [optional]
 */
@property(nonatomic) NSNumber* compoeOfertaValorNaoFinanciavel;
/* {{{configuracao_rotativo_persist_compoe_oferta_valor_novos_lancamentos_value}}} [optional]
 */
@property(nonatomic) NSNumber* compoeOfertaValorNovosLancamentos;
/* {{{configuracao_rotativo_persist_recalcula_parcelamento_para_entrada_maior_value}}} [optional]
 */
@property(nonatomic) NSNumber* recalculaParcelamentoParaEntradaMaior;
/* {{{configuracao_rotativo_persist_minimo_parcelas_recalculo_parcelamento_value}}} [optional]
 */
@property(nonatomic) NSNumber* minimoParcelasRecalculoParcelamento;
/* {{{configuracao_rotativo_persist_recalcula_parcelamento_value}}} [optional]
 */
@property(nonatomic) NSNumber* recalculaParcelamento;
/* {{{configuracao_rotativo_persist_numero_minimo_ofertas_value}}} [optional]
 */
@property(nonatomic) NSNumber* numeroMinimoOfertas;
/* {{{configuracao_rotativo_persist_aceita_pagamento_maior_que_entrada_value}}} [optional]
 */
@property(nonatomic) NSNumber* aceitaPagamentoMaiorQueEntrada;
/* {{{configuracao_rotativo_persist_antecipa_parcelamentos_abertos_value}}} [optional]
 */
@property(nonatomic) NSNumber* antecipaParcelamentosAbertos;
/* {{{configuracao_rotativo_persist_valor_minimo_parcela_value}}} [optional]
 */
@property(nonatomic) NSNumber* valorMinimoParcela;
/* {{{configuracao_rotativo_persist_percentual_limitar_valor_minimo_parcela_value}}} [optional]
 */
@property(nonatomic) NSNumber* percentualLimitarValorMinimoParcela;
/* {{{configuracao_rotativo_persist_id_regra_campanha_value}}} [optional]
 */
@property(nonatomic) NSNumber* idRegraCampanha;
/* {{{configuracao_rotativo_persist_parcelar_apenas_minimo_value}}} [optional]
 */
@property(nonatomic) NSNumber* parcelarApenasMinimo;
/* {{{configuracao_rotativo_persist_usuario_value}}} [optional]
 */
@property(nonatomic) NSString* usuario;

@end
