#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "PierDocumentoDetalheResponse.h"


@protocol PierDocumentoDetalhadoResponse
@end

@interface PierDocumentoDetalhadoResponse : PierObject

/* ID do Documento. [optional]
 */
@property(nonatomic) NSNumber* _id;
/* ID do Template de Documento associado. [optional]
 */
@property(nonatomic) NSNumber* idTemplateDocumento;
/* Nome do Documento. [optional]
 */
@property(nonatomic) NSString* nome;
/* Representa\u00C3\u00A7\u00C3\u00A3o do documento em Base64. [optional]
 */
@property(nonatomic) NSString* documento;
/* Extens\u00C3\u00A3o do Documento. [optional]
 */
@property(nonatomic) NSString* extensao;
/* Detalhamento do documento. [optional]
 */
@property(nonatomic) NSArray<PierDocumentoDetalheResponse>* documentoDetalhes;

@end
