#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierPessoaResponse
@end

@interface PierPessoaResponse : PierObject

/* {{{pessoa_response_id_value}}} 
 */
@property(nonatomic) NSNumber* _id;
/* {{{pessoa_response_nome_value}}} 
 */
@property(nonatomic) NSString* nome;
/* {{{pessoa_response_tipo_value}}} 
 */
@property(nonatomic) NSString* tipo;
/* {{{pessoa_response_cpf_value}}} [optional]
 */
@property(nonatomic) NSString* cpf;
/* {{{pessoa_response_cnpj_value}}} [optional]
 */
@property(nonatomic) NSString* cnpj;
/* {{{pessoa_response_data_nascimento_value}}} [optional]
 */
@property(nonatomic) NSString* dataNascimento;
/* {{{pessoa_response_numero_identidade_value}}} [optional]
 */
@property(nonatomic) NSString* numeroIdentidade;
/* {{{pessoa_response_orgao_expedidor_identidade_value}}} [optional]
 */
@property(nonatomic) NSString* orgaoExpedidorIdentidade;
/* {{{pessoa_response_sexo_value}}} [optional]
 */
@property(nonatomic) NSString* sexo;
/* {{{pessoa_response_unidade_federativa_identidade_value}}} [optional]
 */
@property(nonatomic) NSString* unidadeFederativaIdentidade;
/* {{{pessoa_response_data_emissao_identidade_value}}} [optional]
 */
@property(nonatomic) NSString* dataEmissaoIdentidade;

@end
