#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierPlataformaMobilePersist
@end

@interface PierPlataformaMobilePersist : PierObject

/* Apresenta o nome da plataforma. [optional]
 */
@property(nonatomic) NSString* nome;

@end
