#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierDispositivoResponse
@end

@interface PierDispositivoResponse : PierObject

/* {{{dispositivo_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{dispositivo_response_token_value}}} [optional]
 */
@property(nonatomic) NSString* token;
/* {{{dispositivo_response_id_aplicacao_mobile_value}}} [optional]
 */
@property(nonatomic) NSNumber* idAplicacaoMobile;
/* {{{dispositivo_response_id_usuario_value}}} [optional]
 */
@property(nonatomic) NSNumber* idUsuario;

@end
