#import <Foundation/Foundation.h>
#import "PierObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol PierTelefoneEstabelecimentoResponse
@end

@interface PierTelefoneEstabelecimentoResponse : PierObject

/* {{{telefone_estabelecimento_response_id_value}}} [optional]
 */
@property(nonatomic) NSNumber* _id;
/* {{{telefone_estabelecimento_response_id_estabelecimento_value}}} [optional]
 */
@property(nonatomic) NSNumber* idEstabelecimento;
/* {{{telefone_estabelecimento_response_ddd_value}}} [optional]
 */
@property(nonatomic) NSString* ddd;
/* {{{telefone_estabelecimento_response_telefone_value}}} [optional]
 */
@property(nonatomic) NSString* telefone;
/* {{{telefone_estabelecimento_response_ramal_value}}} [optional]
 */
@property(nonatomic) NSString* ramal;

@end
